googleapis/gapic-generator-ruby

.rubocop.yml, Gemfile, Rakefile, bin/protoc-gen-ruby_gapic, bin/protoc-gen-ruby_gapic_dump, gapic-generator.gemspec, lib/google/gapic/generator.rb, lib/google/gapic/generator/generator.rb, lib/google/gapic/generator/helpers.rb, lib/google/gapic/generator/version.rb, lib/google/gapic/runner.rb, lib/google/gapic/runner/proto_compiler_runner.rb, lib/google/gapic/schema.rb, lib/google/gapic/schema/api.rb, lib/google/gapic/schema/loader.rb, lib/google/gapic/schema/wrappers.rb, test/expected_output/client.rb, test/google/gapic/generator_test.rb, test/templates/client_test.rb, test/templates/gapic_dump_test.rb, test/test_helper.rb
Update the code to adhere to the style guide rules.
[fixes #9]
=> Update Rubocop conformance

Rakefile, gapic-generator-cloud/Rakefile, gapic-generator/Rakefile, shared/Rakefile
Ensures that the protos are compiled before using.
=> Add check_protos rake task

gapic-generator/lib/google/gapic/schema/api.rb, gapic-generator/templates/default/client.erb, gapic-generator/templates/default/shared/_client.erb, shared/Gemfile, shared/Rakefile, shared/config/showcase.yml, shared/input/garbage_desc.yaml, shared/input/showcase_desc.yaml, shared/input/speech_desc.yaml, shared/input/vision_desc.yaml, shared/output/gapic/templates/garbage/endless/trash/forever/garbage_service.rb, shared/output/gapic/templates/showcase/google/showcase/v1alpha3/echo.rb, shared/output/gapic/templates/showcase/google/showcase/v1alpha3/identity.rb, shared/output/gapic/templates/showcase/google/showcase/v1alpha3/messaging.rb, shared/output/gapic/templates/showcase/google/showcase/v1alpha3/testing.rb, shared/output/gapic/templates/speech/google/cloud/speech/v1/speech.rb, shared/output/gapic/templates/vision/google/cloud/vision/v1/image_annotator.rb, shared/output/gapic/templates/vision/google/cloud/vision/v1/product_search.rb, shared/protos/google/showcase/v1alpha3/echo.proto, shared/test/test_helper.rb
Add `showcase.yml`
Update gapic-generator client.erb
Update gapic-generator api.rb
Update shared/test_helper.rb
=> Update generator for Showcase client WIP

gapic-generator-cloud/Rakefile, gapic-generator-cloud/test/google/gapic/generators/cloud_generator_test.rb, shared/config/showcase.yml, shared/output/cloud/showcase/Gemfile, shared/output/cloud/showcase/LICENSE.md, shared/output/cloud/showcase/Rakefile, shared/output/cloud/showcase/google-showcase.gemspec, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo_client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity_client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging_client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing_client.rb, shared/output/cloud/showcase/test/google/showcase/v1alpha3/echo_client_test.rb, shared/output/cloud/showcase/test/google/showcase/v1alpha3/identity_client_test.rb, shared/output/cloud/showcase/test/google/showcase/v1alpha3/messaging_client_test.rb, shared/output/cloud/showcase/test/google/showcase/v1alpha3/testing_client_test.rb, shared/test/showcase/echo_test.rb, shared/test/test_helper.rb
* Add showcase to cloud generator tests
* Update showcase test to use cloud generator
=> Add showcase to cloud generator tests

gapic-generator-cloud/templates/cloud/helpers/cloud_helper.rb
=> Remove usages of protoc_options

gapic-generator-cloud/.rubocop.yml, gapic-generator-cloud/gapic-generator-cloud.gemspec, gapic-generator-cloud/lib/google/gapic/generators/cloud_generator.rb, gapic-generator-cloud/templates/cloud/gemspec.erb, gapic-generator-cloud/templates/cloud/rubocop.erb, shared/output/cloud/showcase/.rubocop, shared/output/cloud/showcase/google-showcase.gemspec, shared/output/cloud/speech/.rubocop, shared/output/cloud/speech/google-cloud-speech.gemspec, shared/output/cloud/vision/.rubocop, shared/output/cloud/vision/google-cloud-vision.gemspec
* Switch cloud generator to google-style
* Add .rubocop to generated files
[closes #74]
=> Switch cloud generator to google-style

gapic-generator-cloud/templates/cloud/client/_client.erb, gapic-generator-cloud/templates/cloud/client/_init.erb, gapic-generator-cloud/templates/cloud/client/method/_init.erb, gapic-generator-cloud/templates/cloud/helpers/presenters/service_presenter.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing.rb, shared/output/cloud/speech/lib/google/cloud/speech/v1/speech.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search.rb
=> Add ServicePresenter#stub_name

gapic-generator-cloud/templates/cloud/helpers/presenters/api_presenter.rb, gapic-generator-cloud/templates/cloud/rakefile.erb
* Lookup value from configuration.
* Fallback by inferring prefix from gem_name.
[closes #59]
=> Refactor product_env_prefix

gapic-generator-cloud/templates/cloud/client/_init.erb, gapic-generator-cloud/templates/cloud/client/method/def/_bidi.erb, gapic-generator-cloud/templates/cloud/client/method/def/_client.erb, gapic-generator-cloud/templates/cloud/client/method/def/_lro.erb, gapic-generator-cloud/templates/cloud/client/method/def/_normal.erb, gapic-generator-cloud/templates/cloud/client/method/def/_server.erb, gapic-generator-cloud/templates/cloud/client_test/_lro.erb, gapic-generator-cloud/templates/cloud/client_test/_normal.erb, gapic-generator-cloud/templates/cloud/client_test/_server.erb, gapic-generator-cloud/templates/cloud/helpers/presenters/method_presenter.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing.rb, shared/output/cloud/speech/lib/google/cloud/speech/v1/speech.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search.rb, shared/test/showcase/echo_test.rb
* Allow request objects to be passed as well as named arguments.
* Individual request field values must now used named arguments.
[refs #69]
=> Update client method signatures

gapic-generator-cloud/lib/google/gapic/generators/cloud_generator.rb
=> Fix the build

README.md, gapic-generator/bin/gapic-generator, gapic-generator/gem_templates/gemfile.erb, gapic-generator/gem_templates/generator.erb, shared/output/gapic/gems/my_plugin/Gemfile, shared/output/gapic/gems/my_plugin/lib/google/gapic/generators/my_plugin_generator.rb
Going through the process of creating a "new" subgenerator and running it against a proto. Collecting fixes here.
=> Fix getting-started experience for new custom generator

gapic-generator/templates/default/service/client/method/def/_options_defaults.erb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/operations.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb, shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb, shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/operations.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/operations.rb, shared/output/gapic/templates/googleads/lib/google/ads/googleads/v1/services/campaign_service/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb, shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb, shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/operations.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/operations.rb
Use the Ruby constant as the value, not a string.
=> Fix header gapic_version value

Dockerfile, docker-entrypoint.sh, gapic.sh
This pull request adds the protobuf and grpc plugins to the Docker image. The Docker image now runs the protobuf, grpc, and gapic (Ruby) plugins. The result is that the output is a complete working library, instead of just the output of the gapic generator.
The Docker image can be run as shown (example usage):
```
Chriss-iMac:gapic-generator-ruby quartzmo$ sh gapic.sh --image gapic-generator-ruby -p /Users/quartzmo/code/google/codez/gapic-generator-ruby/shared/googleapis -i google/ads/googleads/v1 -o /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/test-out-1 --config /Users/quartzmo/code/google/codez/gapic-generator-ruby/shared/config/googleads.yml
```
The output for this example contains all services in `google/ads/googleads/v1`:
<details><summary>Directory listing …
=> Add grpc-tools to Dockerfile

shared/config/googleads.yml, shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
I realised I never upstreamed this from my local config changes.
=> Point at the right googleads domain

gapic-generator/templates/default/helpers/presenters/service_presenter.rb, gapic-generator/templates/default/service/client/_config.erb, shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/operations.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb, shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb, shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb, shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/operations.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb, shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb, shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb, shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/operations.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb, shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/operations.rb
We want to disable service_config by default, use the config to do this.
[closes #190]
=> Add default channel_args config value

shared/test/showcase/echo/echo_test.rb, shared/test/showcase/echo/paged_expand_test.rb
=> Add showcase tests for paged operations

gapic-generator/templates/default/helpers/presenters/field_presenter.rb, gapic-generator/templates/default/service/test/method/_assert_response.erb, gapic-generator/templates/default/service/test/method/_bidi.erb, gapic-generator/templates/default/service/test/method/_client.erb, gapic-generator/templates/default/service/test/method/_normal.erb, gapic-generator/templates/default/service/test/method/_server.erb, gapic-generator/templates/default/service/test/method/_setup.erb, shared/output/cloud/language_v1/test/google/cloud/language/v1/language_service_test.rb, shared/output/cloud/showcase/test/google/showcase/v1beta1/echo_operations_test.rb, shared/output/cloud/showcase/test/google/showcase/v1beta1/echo_test.rb, shared/output/cloud/showcase/test/google/showcase/v1beta1/identity_test.rb, shared/output/cloud/showcase/test/google/showcase/v1beta1/messaging_operations_test.rb, shared/output/cloud/showcase/test/google/showcase/v1beta1/messaging_test.rb, shared/output/cloud/showcase/test/google/showcase/v1beta1/testing_test.rb, shared/output/cloud/vision_v1/test/google/cloud/vision/v1/image_annotator_operations_test.rb, shared/output/cloud/vision_v1/test/google/cloud/vision/v1/product_search_operations_test.rb, shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_operations_test.rb, shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_test.rb, shared/output/gapic/templates/language/test/google/cloud/language/v1/language_service_test.rb, shared/output/gapic/templates/language/test/google/cloud/language/v1beta1/language_service_test.rb, shared/output/gapic/templates/language/test/google/cloud/language/v1beta2/language_service_test.rb, shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/echo_operations_test.rb, shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/messaging_operations_test.rb, shared/output/gapic/templates/speech/test/google/cloud/speech/v1/speech_operations_test.rb, shared/output/gapic/templates/speech/test/google/cloud/speech/v1/speech_test.rb, shared/output/gapic/templates/vision/test/google/cloud/vision/v1/image_annotator_operations_test.rb, shared/output/gapic/templates/vision/test/google/cloud/vision/v1/image_annotator_test.rb, shared/output/gapic/templates/vision/test/google/cloud/vision/v1/product_search_operations_test.rb, shared/output/gapic/templates/vision/test/google/cloud/vision/v1/product_search_test.rb
* Also fix assertions for existing normal tests.
[closes #220]
=> Add templates for streaming unit tests

gapic-generator-cloud/.gcloudignore, gapic-generator-cloud/.gitignore, gapic-generator-cloud/.rubocop.yml, gapic-generator-cloud/Rakefile, gapic-generator-cloud/cloudbuild.yaml
Create a rake task and build scripts to release docker images used by synthtool.
This builds on #321, which should be merged first.
=> feat: rake task for releasing docker images

gapic-generator/templates/default/helpers/presenters/field_presenter.rb, gapic-generator/templates/default/helpers/presenters/method_presenter.rb, gapic-generator/test/gapic/presenters/field_presenter_test.rb, shared/output/ads/googleads/proto_docs/google/ads/googleads/v1/common/bidding.rb, shared/output/ads/googleads/proto_docs/google/ads/googleads/v1/common/frequency_cap.rb, shared/output/ads/googleads/proto_docs/google/ads/googleads/v1/common/targeting_setting.rb, shared/output/ads/googleads/proto_docs/google/ads/googleads/v1/resources/campaign.rb, shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb, shared/output/cloud/language_v1/proto_docs/google/cloud/language/v1/language_service.rb, shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb, shared/output/cloud/language_v1beta1/proto_docs/google/cloud/language/v1beta1/language_service.rb, shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb, shared/output/cloud/language_v1beta2/proto_docs/google/cloud/language/v1beta2/language_service.rb, shared/output/cloud/secretmanager_v1beta1/proto_docs/google/api/resource.rb, shared/output/cloud/secretmanager_v1beta1/proto_docs/google/cloud/secrets/v1beta1/resources.rb, shared/output/cloud/secretmanager_v1beta1/proto_docs/google/iam/v1/policy.rb, shared/output/cloud/speech_v1/proto_docs/google/cloud/speech/v1/cloud_speech.rb, shared/output/cloud/vision_v1/proto_docs/google/api/resource.rb, shared/output/cloud/vision_v1/proto_docs/google/cloud/vision/v1/image_annotator.rb, shared/output/cloud/vision_v1/proto_docs/google/cloud/vision/v1/product_search_service.rb, shared/output/cloud/vision_v1/proto_docs/google/cloud/vision/v1/text_annotation.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb, shared/output/gapic/templates/garbage/proto_docs/garbage/garbage.rb, shared/output/gapic/templates/garbage/proto_docs/google/api/resource.rb, shared/output/gapic/templates/garbage/proto_docs/google/iam/v1/policy.rb, shared/output/gapic/templates/showcase/proto_docs/google/api/resource.rb, shared/output/gapic/templates/showcase/proto_docs/google/showcase/v1beta1/messaging.rb, shared/output/gapic/templates/showcase/proto_docs/google/showcase/v1beta1/testing.rb
=> fix: use full enum module for enum yardoc types

gapic-generator/templates/default/service/client/_client.erb, gapic-generator/templates/default/service/client/_config.erb, shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb, shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb, shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb, shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb, shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb, shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb, shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
=> feat: add yardocs for generated config classes

gapic-generator-cloud/.rubocop.yml, gapic-generator-cloud/Rakefile, gapic-generator-cloud/bin/ruby-cloud-docker-entrypoint, gapic-generator/.rubocop.yml, gapic-generator/Rakefile, gapic-generator/lib/gapic/schema/api.rb, gapic-generator/test/gapic/generators/default_generator_grpc_service_config_test.rb, gapic-generator/test/gapic/grpc_service_config/service_config_parsing_test.rb, shared/Rakefile, shared/gem_defaults.rb, shared/protos/testing/grpc_service_config/grpc_service_config.json, shared/protos/testing/grpc_service_config/grpc_service_config2.json
It looks like cloud billing splits its grpc service config into multiple JSON files, so we need the ability to read multiple files and combine their results.
=> feat: support multiple grpc service config files

gapic-generator/lib/gapic/formatting_utils.rb, gapic-generator/test/gapic/formatting_utils_test.rb
=> fix: Allow additional common characters in cross-reference text

gapic-generator-cloud/lib/gapic/presenters/wrapper_gem_presenter.rb, gapic-generator-cloud/templates/cloud/wrapper_gem/_main.erb, shared/output/cloud/secretmanager_wrapper/lib/google/cloud/secret_manager.rb
=> feat: Support helpers on the wrapper entrypoint

gapic-generator-cloud/bin/ruby-cloud-docker-entrypoint, gapic-generator-cloud/templates/cloud/gem/readme.erb, gapic-generator-cloud/templates/cloud/gem/repo-metadata.erb, gapic-generator-cloud/templates/cloud/wrapper_gem/readme.erb, gapic-generator/lib/gapic/presenters/gem_presenter.rb, shared/output/cloud/language_v1/.repo-metadata.json, shared/output/cloud/language_v1beta1/.repo-metadata.json, shared/output/cloud/language_v1beta2/.repo-metadata.json, shared/output/cloud/noservice/.repo-metadata.json, shared/output/cloud/secretmanager_v1beta1/.repo-metadata.json, shared/output/cloud/secretmanager_wrapper/.repo-metadata.json, shared/output/cloud/speech_v1/.repo-metadata.json, shared/output/cloud/vision_v1/.repo-metadata.json
=> feat: Populate additional repo-metadata fields

gapic-generator-ads/docker-entrypoint.sh
merging Penelope's improvements
CR https://github.com/googleapis/gapic-generator-ruby/pull/472
CR https://github.com/googleapis/gapic-generator-ruby/pull/472#issuecomment-648391338
=> feat: docker entrypoint improvements for ads

gapic-generator-ads/bin/protoc-gen-ruby_ads
merging Penelope's improvements
CR #472
CR https://github.com/googleapis/gapic-generator-ruby/pull/472#issuecomment-648391338
=> feat: add version to the gapic_generator_ads runcommand

bazel_example/gapic-generator/BUILD.bazel, bazel_example/gapic-generator/example.proto, rules_ruby_gapic/ruby_gapic.bzl
make Bazel rules for generator flavors similar and refactor
slight correction to the testing protos
=> feat: unify generator flavor Bazel rules

gapic-common/lib/gapic/call_options/retry_policy.rb, gapic-common/test/gapic/call_options/retry_policy/settings_test.rb, gapic-generator/.rubocop.yml, gapic-generator/lib/gapic/grpc_service_config/parser.rb, gapic-generator/test/gapic/grpc_service_config/service_config_parsing_test.rb, shared/output/ads/googleads/lib/google/ads/googleads/v1/services/campaign_service_services_pb.rb, shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb, shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service_services_pb.rb, shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service_services_pb.rb, shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service_services_pb.rb, shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/cloud_speech_services_pb.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator_services_pb.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search_service_services_pb.rb, shared/output/gapic/templates/garbage/lib/google/iam/v1/iam_policy_services_pb.rb, shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo_services_pb.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity_services_pb.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging_services_pb.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing_services_pb.rb
=> fix: Fix retries by ensuring string error names get converted to their integer codes

gapic-common/lib/gapic/grpc/service_stub.rb, gapic-common/test/gapic/grpc/stub_test.rb, gapic-generator/templates/default/service/client/_config.erb, shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb, shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb, shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb, shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb, shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb, shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb, shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb, shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/iam_policy/client.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/really_renamed_service/client.rb, shared/output/gapic/templates/garbage/lib/so/much/trash/resource_names/client.rb, shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_no_retry/client.rb, shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
=> fix: Support symbol credentials as a special case for grpc

gapic-common/CHANGELOG.md, gapic-common/lib/gapic/common/version.rb
=> fix(common): Rerelease with fixed file permissions

gapic-generator-cloud/lib/gapic/generators/cloud_generator_parameters.rb, gapic-generator-cloud/templates/cloud/gem/readme.erb, gapic-generator/lib/gapic/presenters/gem_presenter.rb, gapic-generator/lib/gapic/presenters/service_presenter.rb, gapic-generator/templates/default/gem/readme.erb, shared/config/vision_v1.yml, shared/output/cloud/compute_small/README.md, shared/output/cloud/language_v1/README.md, shared/output/cloud/language_v1beta1/README.md, shared/output/cloud/language_v1beta2/README.md, shared/output/cloud/secretmanager_v1beta1/README.md, shared/output/cloud/speech_v1/README.md, shared/output/cloud/vision_v1/README.md, shared/output/gapic/templates/garbage/README.md, shared/output/gapic/templates/grpc_service_config/README.md, shared/output/gapic/templates/showcase/README.md
=> feat: Support configuring the preferred quickstart service/method

gapic-generator-ads/Gemfile.lock, gapic-generator-cloud/Gemfile.lock, gapic-generator-cloud/templates/cloud/gem/authentication.erb, gapic-generator/Gemfile.lock, shared/output/cloud/compute_small/AUTHENTICATION.md, shared/output/cloud/language_v1/AUTHENTICATION.md, shared/output/cloud/language_v1beta1/AUTHENTICATION.md, shared/output/cloud/language_v1beta2/AUTHENTICATION.md, shared/output/cloud/secretmanager_v1beta1/AUTHENTICATION.md, shared/output/cloud/secretmanager_wrapper/AUTHENTICATION.md, shared/output/cloud/speech_v1/AUTHENTICATION.md, shared/output/cloud/vision_v1/AUTHENTICATION.md
refs: googleapis/google-cloud-ruby#12532
=> fix: Update cloud/gem/authentication.erb

gapic-generator/lib/gapic/schema/api.rb
This fixes an issue discovered when migrating google/monitoring/v3 generation from docker to bazel.
The [protos](https://github.com/googleapis/googleapis/blob/master/google/monitoring/v3/metric_service.proto) define a resource type `monitoring.googleapis.com/Workspace` that maps to several patterns including `projects/*`. This overlaps with the standard type `cloudresourcemanager.googleapis.com/Project` which maps to the same pattern, making it ambiguous which resource is intended when that pattern is in use. Currently, the code that determines resource parentage assumes that each pattern maps to at most one resource type. If there is overlap, it will choose one based on _load order_ of the input proto files. Thus, parentage computation is load-order dependent.
When migrating Monitoring …
=> fix: Detect multiple resource parents for patterns used by multiple resources

gapic-generator/Rakefile, gapic-generator/lib/gapic/presenters/gem_presenter.rb, gapic-generator/lib/gapic/presenters/service_presenter.rb, gapic-generator/test/gapic/presenters/gem/mixins_test.rb, gapic-generator/test/gapic/presenters/method/rest_lro_test.rb
wanted some presenter-level tests when investigating some merge-rebase issues
=> feat: add some presenter tests

gapic-generator-cloud/templates/cloud/gem/authentication.erb, shared/output/cloud/compute_small/AUTHENTICATION.md, shared/output/cloud/compute_small_wrapper/AUTHENTICATION.md, shared/output/cloud/language_v1/AUTHENTICATION.md, shared/output/cloud/language_v1beta1/AUTHENTICATION.md, shared/output/cloud/language_v1beta2/AUTHENTICATION.md, shared/output/cloud/secretmanager_v1beta1/AUTHENTICATION.md, shared/output/cloud/secretmanager_wrapper/AUTHENTICATION.md, shared/output/cloud/speech_v1/AUTHENTICATION.md, shared/output/cloud/vision_v1/AUTHENTICATION.md
=> fix: Remove broken links and fix outdated content in the auth template

renovate.json
=> chore: remove the dependency dashboard

gapic-generator-ads/test/generators/ads_test.rb, gapic-generator/lib/gapic/presenters/gem_presenter.rb, shared/Rakefile
=> fix: can generate noservice

gapic-common/gapic-common.gemspec, gapic-common/test/gapic/grpc/stub_test.rb, gapic-generator-ads/Gemfile.lock, gapic-generator-ads/gapic-generator-ads.gemspec, gapic-generator-cloud/Gemfile.lock, gapic-generator-cloud/gapic-generator-cloud.gemspec, gapic-generator/Gemfile.lock, gapic-generator/gapic-generator.gemspec, gapic/gapic.gemspec
Workaround for https://github.com/minitest/minitest/issues/912
=> chore: Update tests for compatibility with minitest 5.16

gapic-common/lib/gapic/headers.rb, gapic-common/test/gapic/headers/x_goog_api_client_test.rb
=> feat: send protobuf version in headers

gapic-common/.rubocop.yml, gapic-common/lib/gapic/rest/server_stream.rb, gapic-common/test/gapic/rest/server_stream_test.rb, gapic-generator/lib/gapic/presenters/method_rest_presenter.rb, gapic-generator/templates/default/service/rest/client/method/def/_response.erb, gapic-generator/templates/default/service/rest/client/method/def/_response_server_streaming.erb, gapic-generator/templates/default/service/rest/service_stub/method/_def.erb, gapic-generator/templates/default/service/rest/service_stub/method/def/_response.erb, gapic-generator/templates/default/service/rest/test/method/_server.erb, gapic-generator/test/gapic/presenters/method/rest_test.rb, gapic-generator/test/gapic/presenters/service/showcase_echo_rest_test.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/service_stub.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/rest/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/rest/service_stub.rb, shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/echo_rest_test.rb, shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/messaging_rest_test.rb, shared/test/showcase/echo/expand_test.rb
- restore server streaming generation
- generate changes in showcase
- add integration test with showcase
- minor fixes (e.g. json decoding allows unknown fields)
=> feat: fix to clean templates

gapic-common/.rubocop.yml, gapic-common/lib/gapic/rest/client_stub.rb, gapic-common/lib/gapic/rest/server_stream.rb, gapic-common/lib/gapic/rest/threaded_enumerator.rb, gapic-common/test/gapic/rest/server_stream_test.rb, gapic-common/test/gapic/rest/threaded_enumerator_test.rb
Implements changes for server-side streaming to gapic-common.
=> feat: implement sever-side stream changes to gapic-common

gapic-common/lib/gapic/call_options.rb, gapic-common/lib/gapic/call_options/error_codes.rb, gapic-common/lib/gapic/call_options/retry_policy.rb, gapic-common/lib/gapic/rest/client_stub.rb, gapic-common/test/gapic/call_options/retry_policy/call_test.rb
re: https://github.com/googleapis/gapic-generator-ruby/issues/841 2/3
template changes to follow
=> feat: make retry policy work with REST

gapic-generator/templates/default/service/rest/client/_config.erb, gapic-generator/templates/default/service/rest/client/method/def/_options_defaults.erb, gapic-generator/templates/default/service/rest/client/method/docs/_request.erb, shared/output/cloud/compute_small/lib/google/cloud/compute/v1/addresses/rest/client.rb, shared/output/cloud/compute_small/lib/google/cloud/compute/v1/global_operations/rest/client.rb, shared/output/cloud/compute_small/lib/google/cloud/compute/v1/networks/rest/client.rb, shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_instance_group_managers/rest/client.rb, shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_operations/rest/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/compliance/rest/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/rest/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/rest/client.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/rest/operations.rb, shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/rest/client.rb
fixes https://github.com/googleapis/gapic-generator-ruby/issues/841
=> feat: use retry policy in regapic templates

gapic-generator/lib/gapic/file_formatter.rb
fixes #919 
This was a little tricky because Rubocop itself returns a nonzero status code if it detected (and fixed) formatting issues, and we don't want those to trigger an error. So instead we check for exceptions, and ignore Rubocop's return value.
=> fix(gapic-generator): Fail generation if Rubocop autoformatting fails

gapic-generator/lib/gapic/model/api_metadata.rb, gapic-generator/test/gapic/model/api_metadata_test.rb
See internal issue b/247778923
=> fix: Fix special case iam API shortname

gapic-common/lib/gapic/call_options.rb, gapic-common/lib/gapic/config.rb, gapic-common/lib/gapic/generic_lro/operation.rb, gapic-common/lib/gapic/operation.rb, gapic-common/lib/gapic/rest/grpc_transcoder.rb, gapic-common/lib/gapic/rest/transport_operation.rb
=> docs(gapic-common): Minor fixes to YARD documentation links and parameters

.github/workflows/ci-common.yml, gapic-common/Gemfile, gapic-common/gapic-common.gemspec
fixes #1080 
Dependent on the grpc 1.65.0 final release. Will remain in draft mode for testing until then.
=> feat(common): Support for protobuf 4.x

gapic-generator/lib/gapic/presenters/gem_presenter.rb
Issue was shown while testing generator `v0.34.0` changes.
=> fix: Add missing api parameter to gem_presenter

gapic-common/lib/gapic/grpc/service_stub/rpc_call.rb, gapic-common/lib/gapic/headers.rb, gapic-common/test/gapic/grpc/rpc_call/retry/raise_test.rb, gapic-common/test/gapic/grpc/rpc_call/retry/retry_test.rb
=> fix(gapic-common): Hardened deadline determination against Time.now hacking

gapic-generator-ads/.toys.rb, gapic-generator-cloud/.toys.rb, gapic-generator/.toys/.toys.rb
This should fix the internal gem releases.
=> chore: Provide build tool for release scripts

.kokoro/bazel-test.sh
Adds a test to ensure the ads generation runs too
=> test: try to build a googleads library during presubmit

gapic-generator-cloud/templates/cloud/wrapper_gem/readme.text.erb, shared/output/cloud/compute_small_wrapper/README.md, shared/output/cloud/language_wrapper/README.md, shared/output/cloud/secretmanager_wrapper/README.md
Closes https://github.com/googleapis/gapic-generator-ruby/issues/1218
=> feat: add quick start to wrappers README
