googleapis/gapic-generator-ruby

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Any objections to adding the standard `CODE_OF_CONDUCT`? I didn't add it here yet but I think we should.
[fixes #22]
> Add standard contributing guidelines

- .circleci/config.yml
- Rakefile
- shared/Gemfile
- shared/Rakefile
- shared/test/showcase/echo_test.rb
- shared/test/test_helper.rb
I would like to be able to have folks do something along the lines #44 for the demo next week. They should be able to build an API (showcase in particular) using just a simple Gemfile/Rakefile pair that will take care of installing everything beyond Ruby and bundler. We'll also show how to write a simple script to use the generated library (and we'll likely have rake run it after generation so it's a one liner demo) i.e.:
```ruby
require "google/showcase/v1alpha3/echo"
client = Google::Showcase::V1alpha3::EchoClient.new(
credentials: GRPC::Core::Channel.new(
"localhost:7469", nil, :this_channel_is_insecure))
response = client.echo 'hi there!', nil
puts response.content
```
However, we need to get this test that I've added to pass in order to do that. I was able to edit the generated files …
> Add failing test for demo prep

- gapic-generator/lib/google/gapic/schema/wrappers.rb
- gapic-generator/test/google/gapic/annotations/package_test.rb
Enable the `client_package` annotation by adding a parent reference to the schema objects.
> Add client package annotation

- gapic-generator-cloud/lib/google/gapic/generators/cloud_generator.rb
- gapic-generator-cloud/templates/cloud/client/_client.erb
- gapic-generator-cloud/templates/cloud/rakefile.erb
- gapic-generator/.rubocop.yml
- gapic-generator/gem_templates/generator.erb
- gapic-generator/lib/google/gapic/generators/base_generator.rb
- gapic-generator/lib/google/gapic/generators/default_generator.rb
- shared/output/cloud/showcase/Rakefile
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing.rb
- shared/output/cloud/showcase/test/google/showcase/v1alpha3/echo_test.rb
- shared/output/cloud/showcase/test/google/showcase/v1alpha3/messaging_test.rb
- shared/output/cloud/speech/Rakefile
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech.rb
- shared/output/cloud/speech/test/google/cloud/speech/v1/speech_test.rb
- shared/output/cloud/vision/Rakefile
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search.rb
- shared/output/cloud/vision/test/google/cloud/vision/v1/image_annotator_test.rb
- shared/output/cloud/vision/test/google/cloud/vision/v1/product_search_test.rb
- shared/output/gapic/gems/my_plugin/lib/google/gapic/generators/my_plugin_generator.rb
Move the formatter into the base generator.
Rename the generate_file method, add convenience name as alias.
Add config method that allows plugin generators to override
the location of the configuration file to use to format.
Add formatter code as separate method so it can also be
overridden. (Hi, rubyfmt)
Fix the formatter so it works in the cloud generator.
> Refactor base generator code formatting

- gapic-generator-cloud/lib/google/gapic/generators/cloud_generator.rb
- gapic-generator-cloud/templates/cloud/client/_client.erb
- gapic-generator-cloud/templates/cloud/gemspec.erb
- gapic-generator-cloud/templates/cloud/helpers/presenters/api_presenter.rb
- gapic-generator-cloud/templates/cloud/helpers/presenters/service_presenter.rb
- gapic-generator-cloud/templates/cloud/package/_version.erb
- gapic-generator-cloud/templates/cloud/version.erb
- shared/output/cloud/showcase/google-showcase.gemspec
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing.rb
- shared/output/cloud/showcase/lib/google/showcase/version.rb
- shared/output/cloud/speech/google-cloud-speech.gemspec
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech.rb
- shared/output/cloud/speech/lib/google/cloud/speech/version.rb
- shared/output/cloud/vision/google-cloud-vision.gemspec
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search.rb
- shared/output/cloud/vision/lib/google/cloud/vision/version.rb
This PR adds a version file and a `VERSION` constant that is used in the client's grpc headers instead of looking up the gem version from RubyGems.
> Add a gem version file and constant

- gapic-generator-cloud/lib/google/gapic/generators/cloud_generator.rb
- gapic-generator-cloud/templates/cloud/client/_class.erb
- gapic-generator-cloud/templates/cloud/client/_paths.erb
- gapic-generator-cloud/templates/cloud/client/_resource.erb
- gapic-generator-cloud/templates/cloud/client/paths.erb
- gapic-generator-cloud/templates/cloud/helpers/presenters/resource_presenter.rb
- gapic-generator-cloud/templates/cloud/helpers/presenters/service_presenter.rb
- gapic-generator/lib/google/gapic/template.rb
- gapic-generator/lib/google/gapic/template/parser.rb
- gapic-generator/lib/google/gapic/template/segment.rb
- gapic-generator/test/google/gapic/template/empty_test.rb
- gapic-generator/test/google/gapic/template/named_test.rb
- gapic-generator/test/google/gapic/template/positional_test.rb
- gapic-generator/test/test_helper.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/paths.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/paths.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/paths.rb
This module includes helper methods to create resource strings.
This module is included and extended in the Client class.
This module can be used by users without creating a client object.
[closes #76, #6]
> Add Paths module for a service

- gapic-generator/lib/google/gapic/schema/loader.rb
- gapic-generator/test/google/gapic/annotations/enum_test.rb
Looks like the problem was the `@prior_enums` member was not populated when the messages were loading their fields.
> Fix enum loading

- gapic-generator-cloud/templates/cloud/client/_resource.erb
- gapic-generator-cloud/templates/cloud/helpers/presenters/resource_presenter.rb
- gapic-generator/Rakefile
- gapic-generator/lib/google/gapic/generators/default_generator.rb
- gapic-generator/lib/google/gapic/path_template.rb
- gapic-generator/lib/google/gapic/path_template/parser.rb
- gapic-generator/lib/google/gapic/path_template/segment.rb
- gapic-generator/test/google/gapic/path_template/empty_path_template_test.rb
- gapic-generator/test/google/gapic/path_template/named_path_template_test.rb
- gapic-generator/test/google/gapic/path_template/positional_path_template_test.rb
- gapic-generator/test/test_helper.rb
To mitigate a major naming conflict with ERB templates:
* Rename `Template` to `PathTemplate`, including variable names, accessors, tests, etc.
* Update documentation with links to URI Template spec.
> Rename Gapic::Template to Gapic::PathTemplate

- gapic-generator-cloud/lib/google/gapic/generators/cloud_generator.rb
- gapic-generator/lib/google/gapic/file_formatter.rb
- gapic-generator/lib/google/gapic/generators/base_generator.rb
- gapic-generator/lib/google/gapic/generators/default_generator.rb
I have been having some pain regenerating the libraries since it takes quite a while since rubocop runs individually per file making it really slow.
```sh
$ time bundle exec rake gen
...
> bundle exec rake gen  134.99s user 52.76s system 98% cpu 3:10.42 total
```
```sh
$ time bundle exec rake gen
...
> bundle exec rake gen  35.73s user 8.23s system 98% cpu 44.503 total
```
> Run rubocop autocorrect on a dir rather than per file

- Rakefile
- gapic-generator-cloud/Rakefile
- gapic-generator/.gitignore
- gapic-generator/README.md
- gapic-generator/Rakefile
- gapic-generator/lib/google/api/annotations.pb.rb
- gapic-generator/lib/google/api/client.pb.rb
- gapic-generator/lib/google/api/field_behavior.pb.rb
- gapic-generator/lib/google/api/http.pb.rb
- gapic-generator/lib/google/api/resource.pb.rb
- gapic-generator/lib/google/longrunning/operations.pb.rb
- gapic-generator/lib/google/protobuf/any.pb.rb
- gapic-generator/lib/google/protobuf/compiler/plugin.pb.rb
- gapic-generator/lib/google/protobuf/descriptor.pb.rb
- gapic-generator/lib/google/protobuf/empty.pb.rb
- gapic-generator/lib/google/rpc/status.pb.rb
- shared/Rakefile
This PR adds the ruby files generated by protobuf (not google-protobuf) to the repo. New files can be generated by calling the default generator's `gen:protos` task.
This allows the gem to be referenced from the git repo.
[fixes #44]
> Add protobuf files

- gapic-generator/templates/default/client/_class.erb
- gapic-generator/templates/default/client/_init.erb
- gapic-generator/templates/default/client/lro/_init.erb
- shared/Gemfile
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
Use a more familiar convention for creating a Gax Stub object.
The GAX side of this change is: googleapis/gax-ruby#180
> Use Google::Gax::Grpc::Stub.new

- gapic-generator/templates/default/client/method/def/_options_defaults.erb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
Remove the generated placeholder until retry behavior is decided on.
> Remove retry_policy

- gapic-generator/templates/default/client/method/def/_paged.erb
- gapic-generator/templates/default/client_test/_paged.erb
- gapic-generator/templates/default/helpers/presenters/method_presenter.rb
- gapic-generator/test/google/gapic/presenters/method/paged_test.rb
- shared/Gemfile
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/test/showcase/echo/chat_test.rb
- shared/test/showcase/echo/echo_test.rb
- shared/test/showcase/echo/expand_test.rb
- shared/test/showcase/echo/paged_expand_test.rb
- shared/test/test_helper.rb
Add paging support in the default generator. Add showcase tests for Expand and PagedExpand.
This change requires googleapis/gax-ruby#182 to be merged first.
> Add Pagination support

- gapic-generator/lib/google/gapic/gem_builder.rb
- gapic-generator/templates/default/helpers/namespace_helper.rb
- gapic-generator/templates/default/helpers/presenters/field_presenter.rb
- gapic-generator/templates/default/helpers/presenters/gem_presenter.rb
- gapic-generator/templates/default/helpers/presenters/message_presenter.rb
- gapic-generator/templates/default/helpers/presenters/method_presenter.rb
- gapic-generator/templates/default/helpers/presenters/service_presenter.rb
- gapic-generator/templates/default/layouts/_ruby.erb
- shared/output/cloud/showcase/proto_docs/google/protobuf/descriptor.rb
- shared/output/cloud/speech/proto_docs/google/protobuf/descriptor.rb
- shared/output/cloud/vision/proto_docs/google/cloud/vision/v1/image_annotator.rb
- shared/output/cloud/vision/proto_docs/google/cloud/vision/v1/product_search.rb
- shared/output/cloud/vision/proto_docs/google/protobuf/descriptor.rb
- shared/output/gapic/templates/showcase/proto_docs/google/protobuf/descriptor.rb
- shared/output/gapic/templates/speech/proto_docs/google/protobuf/descriptor.rb
- shared/output/gapic/templates/vision/proto_docs/google/cloud/vision/v1/image_annotator.rb
- shared/output/gapic/templates/vision/proto_docs/google/cloud/vision/v1/product_search.rb
- shared/output/gapic/templates/vision/proto_docs/google/protobuf/descriptor.rb
Switch to using `camelize` instead of `classify`, which was singularizing the names.
> Fix unintentionally singularizing names

- Dockerfile
- docker-entrypoint.sh
- gapic.sh
Support language-agnostic build pipeline. This hook is currently implemented in the top-level of the repo, but only targets `gapic-generator`.
The `gapic.sh` file executes `docker run`, then within the Docker image the `docker-entrypoint.sh` file calls `protoc`.
[gapic.sh](https://github.com/googleapis/gapic-generator-python/blob/master/gapic.sh)
[docker-entrypoint.sh](https://github.com/googleapis/gapic-generator-python/blob/master/docker-entrypoint.sh)
[gapic.sh](https://github.com/googleapis/gapic-generator-go/blob/master/gapic.sh)
[docker-entrypoint.sh](https://github.com/googleapis/gapic-generator-go/blob/master/docker-entrypoint.sh)
The notable addition to `gapic.sh` in Ruby is the `--config` option.
```sh
gapic-generator-ruby$ docker build -t gapic-generator-ruby . …
```
> Add Dockerfile and gapic.sh

- gapic-generator/templates/default/service/client/_client.erb
- gapic-generator/templates/default/service/client/_config.erb
- gapic-generator/templates/default/service/client/_operations.erb
- shared/Gemfile
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/operations.rb
This PR adds the `channel_args` value to the client's `Configuration` object. This config value allows users to control the behavior of the GRPC client object, including setting the size of the maximum request and response messages. Using the configuration object to set this value seems like the most appropriate and expected mechanism.
This PR is dependent on `channel_args` being added to Gax in googleapis/gax-ruby#201.
> Gax stub channel args

- gapic-generator/templates/default/helpers/presenters/method_presenter.rb
- gapic-generator/templates/default/service/client/method/def/_response.erb
- gapic-generator/test/google/gapic/presenters/method_test.rb
- shared/Gemfile
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/operations.rb
Implement calling the RPC by calling a method on the Stub object instead of creating an ApiCall object. This reduces the number of instance variables on the client object.
Dependent on googleapis/gax-ruby#206.
>  Use the Gax gRPC stub object

- gapic-generator/templates/default/service/client/method/def/_options_defaults.erb
- shared/Gemfile
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/googleads/lib/google/ads/googleads/v1/services/campaign_service/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/operations.rb
Move this common code to Gax so the GAPIC client can do less. This is dependent on googleapis/gax-ruby#210.
>  Use Gax header helper

- gapic-generator/templates/default/service/client/method/docs/_request_normal.erb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/googleads/lib/google/ads/googleads/v1/services/campaign_service/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/operations.rb
The named arg method docs were removed when the methods were switched
to use positional args. This change restores the previous named arg
docs, except the named args cannot specify the optional call options.
This demonstrates how we can use the positonal args as named args.
> Restore named argument documentation

- gapic-generator-ads/Dockerfile
- gapic-generator-ads/Gemfile
- gapic-generator-ads/LICENSE
- gapic-generator-ads/Rakefile
- gapic-generator-ads/docker-entrypoint.sh
- gapic-generator-ads/gapic-generator-ads.gemspec
- gapic-generator-cloud/Dockerfile
- gapic-generator-cloud/Rakefile
- gapic-generator-cloud/gapic-generator-cloud.gemspec
- gapic-generator/gapic-generator.gemspec
- gapic-generator/gem_templates/gemspec.erb
- shared/output/gapic/gems/my_plugin/gapic-generator-my_plugin.gemspec
Applies the changes in #162 to the gapic-generator-ads directory. This should allow invocation of the ads generator.
* Create `gapic-generator-ads/Dockerfile` and `gapic-generator-ads/docker-entrypoint.sh`.
* Add `image` and `image:local` rake tasks to gapic-generator-ads.
* Update gapic-generator-ads.gemspec so it doesn't invoke git.
Also some other fixes and cleanup:
* Fix a cloud->ads typo in `gapic-generator-ads/Gemfile`.
* Add `gapic-generator-ads/LICENSE` file.
* Remove a permissions hack from the other Dockerfiles now that google-style 0.3.1 is released.
* Fix a crash in gapic-generator-cloud's `image:local` rake task.
* Fix the gemspec for new subgenerator gems so they don't try to include files that are not part of the subgenerator as initially generated.
> Add docker entrypoint for ads

- gapic-generator-ads/docker-entrypoint.sh
Update the Google Ads docker image to change the file paths of the files generated by the protobuf and grpc plugins.
> Update Google Ads Docker file paths

- gapic-generator-ads/docker-entrypoint.sh
This PR corrects the protoc-gen-grpc output to so the referenced messages correctly honors the `ruby_package` set in the Google Ads protos. This is a manual fix and will only work for Google Ads until the upstream bug is fixed. (See grpc/grpc#19438)
With this patch, you can generate the Google Ads ruby files using the following:
```sh
cd ~/gapic-generator-ruby
cd gapic-generator-ads
bundle exec rake image:local
cd ..
rm -rf ads-output
mkdir -p ads-output
sh gapic.sh --image ruby-gapic-generator-ads -p `pwd`/shared/googleapis -i google/ads/googleads/v1 -o ../../ads-output --config ../config/googleads.yml
```
Then grepping the output for "Googleads" only returns the README for the YARD documentation directory:
```
$ grep -r "Googleads" ads-output
ads-output/proto_docs/README.md:# Google Ads …
```
> Patch protoc grpc plugin output

- gapic-generator-ads/Rakefile
This is done so that we know exactly to which code we're referring
before we bake our container and so that we can switch back and forth
easily.
> Use current git SHA as image tag for ads docker image.

- gapic-generator/templates/default/helpers/presenters/file_presenter.rb
- gapic-generator/templates/default/helpers/presenters/package_presenter.rb
- gapic-generator/test/google/gapic/presenters/file/garbage_test.rb
- gapic-generator/test/google/gapic/presenters/file/googleads_test.rb
- gapic-generator/test/google/gapic/presenters/file/showcase_test.rb
- gapic-generator/test/google/gapic/presenters/file/speech_test.rb
- gapic-generator/test/google/gapic/presenters/file/vision_test.rb
- gapic-generator/test/google/gapic/presenters/gem/garbage_test.rb
- gapic-generator/test/google/gapic/presenters/gem/googleads_test.rb
- gapic-generator/test/google/gapic/presenters/gem/showcase_test.rb
- gapic-generator/test/google/gapic/presenters/gem/speech_test.rb
- gapic-generator/test/google/gapic/presenters/gem/vision_test.rb
- gapic-generator/test/google/gapic/presenters/package/garbage_test.rb
- gapic-generator/test/google/gapic/presenters/package/googleads_test.rb
- gapic-generator/test/google/gapic/presenters/package/showcase_test.rb
- gapic-generator/test/google/gapic/presenters/package/speech_test.rb
- gapic-generator/test/google/gapic/presenters/package/vision_test.rb
Add tests for the following:
* GemPresenter
* FilePresenter
* PackagePresenter
[refs #173]
> Add presenter tests

- gapic-generator/templates/default/service/client/method/def/_options_defaults.erb
- shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/cloud/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1alpha3/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/gapic/templates/vision/lib/google/cloud/vision/v1/product_search/operations.rb
Don't over-specify the RPC call options.
Allow the GRPC client to use its configured timeout setting.
[closes #192]
> Don't use client timeout on RPC calls

- gapic-generator-cloud/lib/gapic/generators/cloud_generator.rb
- gapic-generator-cloud/templates/cloud/gem/_slashed.erb
- gapic-generator-cloud/templates/cloud/gem/dashed.erb
- gapic-generator-cloud/templates/cloud/gem/slashed.erb
- gapic-generator-cloud/templates/cloud/service/client/_client.erb
- shared/output/cloud/showcase/lib/google-showcase.rb
- shared/output/cloud/showcase/lib/google/showcase.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/testing/client.rb
- shared/output/cloud/speech/lib/google-cloud-speech.rb
- shared/output/cloud/speech/lib/google/cloud/speech.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/vision/lib/google-cloud-vision.rb
- shared/output/cloud/vision/lib/google/cloud/vision.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
Cloud defines these dashed and slashed files. As we work towards supporting more current Cloud-specific features we will want these files.
This PR also defines a Gem-level configuration that can set common values above the package/version level or the service/client level.
> Add gem dashed and slashed files

- shared/test/showcase/echo/chat_test.rb
- shared/test/showcase/echo/collect_test.rb
- shared/test/showcase/echo/echo_test.rb
- shared/test/showcase/echo/expand_test.rb
- shared/test/showcase/echo/operations_test.rb
- shared/test/showcase/echo/paged_expand_test.rb
- shared/test/showcase/echo/wait_test.rb
- shared/test/test_helper.rb
Ads tests for new methods in showcase 0.4.0 and consolidate all the `Google::Showcase::V1beta1::Echo::Client.new` calls.
Note that `list_operations` produces a oneof deserialization error when used with the `page_size` parameter. I don't think it's critical that these tests cover that (it may be a server side issue), but I could not figure out why the error is thrown.
> Add tests for showcase operations client

- gapic-common/.rubocop.yml
- gapic-common/lib/gapic/config.rb
- gapic-generator-ads/.rubocop.yml
- gapic-generator-ads/lib/gapic/generators/ads_generator.rb
- gapic-generator/.rubocop.yml
- gapic-generator/lib/gapic/schema/loader.rb
- gapic-generator/templates/default/helpers/presenters/enum_presenter.rb
- gapic-generator/templates/default/helpers/presenters/enum_value_presenter.rb
- gapic-generator/templates/default/helpers/presenters/field_presenter.rb
- gapic-generator/templates/default/helpers/presenters/file_presenter.rb
- gapic-generator/templates/default/helpers/presenters/message_presenter.rb
- gapic-generator/templates/default/helpers/presenters/method_presenter.rb
- gapic-generator/templates/default/helpers/presenters/resource_presenter.rb
- gapic-generator/templates/default/helpers/presenters/service_presenter.rb
- shared/.rubocop.yml
- shared/Gemfile
- shared/Rakefile
A series of small refactors to satisfy rubocop and adds a rubocop config to the `shared` project. 
It does not quite finish #191. The following exclusions still remain, but I'm not sure any are worth tackling now:
+ equality issue (gapic-common)
+ Missing documentation (many gems)
+ Long presenter classes (seems ok to me)
+ Tests (seems ok to me)
+ All cops disabled in the `cloud_generator` and `ads_generator`
> Remove most rubocop exclusions

- gapic-common/lib/gapic/paged_enumerable.rb
- gapic-common/test/gapic/paged_enumerable/format_resource_test.rb
Refactor the responsibility for applying a resource format from the PagedEnumerable to the PagedEnumerable's Page object. Fixes an issue where the formatting wasn't applied when accessing the paged resource from a Page object.
Extracted from #228.
> Refactor PagedEnumerable format_resource

- gapic-common/lib/gapic/call_options.rb
- gapic-common/lib/gapic/grpc/service_stub/rpc_call.rb
- gapic-common/test/gapic/call_options/settings_test.rb
- gapic-common/test/gapic/grpc/rpc_call/raise_test.rb
- gapic-common/test/gapic/grpc/rpc_call/retry/raise_test.rb
- gapic-common/test/gapic/grpc/rpc_call/retry/retry_test.rb
- gapic-common/test/gapic/grpc/rpc_call/rpc_call_test.rb
When timeout is nil or negative the RPC call will not specify a call deadline.
This is important for streaming calls that do not want a deadline.
> Allow call options timeout to be nil or negative

- gapic-common/test/gapic/call_options/retry_policy/call_test.rb
- gapic-common/test/gapic/call_options/retry_policy/settings_test.rb
- gapic-common/test/gapic/call_options/settings_test.rb
- gapic-common/test/gapic/error_test.rb
- gapic-common/test/gapic/gax_error/status_details_test.rb
- gapic-common/test/gapic/grpc/rpc_call/raise_test.rb
- gapic-common/test/gapic/grpc/rpc_call/retry/raise_test.rb
- gapic-common/test/gapic/grpc/rpc_call/retry/retry_test.rb
- gapic-common/test/gapic/grpc/rpc_call/rpc_call_test.rb
These tests complete when running in one job, but they are missing
needed requires when running in isolation, e.g. autotest.
> Add missing test requires

- Rakefile
Split the binary file creation and template generation tasks. We so rarely generate binary files and it is much slower. This speeds up development by allowing for quicker/easier template generation.
This PR is a draft until other PRs are merged.
> Separate Rakefile binary file and template generation tasks

- gapic-generator-cloud/templates/cloud/service/client/_requires.erb
- gapic-generator-cloud/templates/cloud/service/client/_self_configure.erb
- shared/output/cloud/language/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/cloud/language/lib/google/cloud/language/v1beta1/language_service/client.rb
- shared/output/cloud/language/lib/google/cloud/language/v1beta2/language_service/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/cloud/showcase/lib/google/showcase/v1beta1/testing/client.rb
- shared/output/cloud/speech/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision/lib/google/cloud/vision/v1/product_search/client.rb
Instead of adding a require to the client file, check the namespace for a constant that has a configure method. This will come in handy if/when we have service-specific gems, such as google-cloud-spanner-v1. Those gems won't have a dependency on google-cloud-spanner, and so they should not have a require for it, and dynamically find the parent configure object instead.
> Dynamically traverse Cloud namespace for configure

- gapic-common/Gemfile
- gapic-common/gapic-common.gemspec
- gapic-common/lib/gapic/config.rb
- gapic-common/test/gapic/config/core_config_test.rb
We need a small change to interop with google-cloud-core. We should use `BasicObject#__send__` instead of `Object#send`.
> Add google-cloud-core Config interop

- gapic-common/CHANGELOG.md
- gapic-common/gapic-common.gemspec
- gapic-common/lib/gapic/common/version.rb
I don't think we have releasetool set up for this repo. So releasing manually.
> Release gapic-common 0.1.0

- gapic-generator-cloud/templates/cloud/gem/gemspec.erb
- gapic-generator/templates/default/gem/gemfile.erb
- gapic-generator/templates/default/gem/gemspec.erb
- shared/output/cloud/language_v1/Gemfile
- shared/output/cloud/language_v1/google-cloud-language-v1.gemspec
- shared/output/cloud/language_v1beta1/Gemfile
- shared/output/cloud/language_v1beta1/google-cloud-language-v1beta1.gemspec
- shared/output/cloud/language_v1beta2/Gemfile
- shared/output/cloud/language_v1beta2/google-cloud-language-v1beta2.gemspec
- shared/output/cloud/secretmanager_v1beta1/Gemfile
- shared/output/cloud/secretmanager_v1beta1/google-cloud-secret_manager-v1beta1.gemspec
- shared/output/cloud/speech_v1/Gemfile
- shared/output/cloud/speech_v1/google-cloud-speech-v1.gemspec
- shared/output/cloud/vision_v1/Gemfile
- shared/output/cloud/vision_v1/google-cloud-vision-v1.gemspec
- shared/output/gapic/templates/garbage/Gemfile
- shared/output/gapic/templates/garbage/google-garbage.gemspec
- shared/output/gapic/templates/showcase/Gemfile
- shared/output/gapic/templates/showcase/google-showcase.gemspec
* Use released version of gapic-common
* Use released version of google-cloud-errors
> Update runtime dependencies in generated files

- gapic-generator/templates/default/helpers/presenters/resource_presenter.rb
- gapic-generator/templates/default/service/client/_resource.erb
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/paths.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/paths.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/paths.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/paths.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/paths.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/paths.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/paths.rb
As discussed in https://github.com/googleapis/gapic-generator-ruby/pull/313#discussion_r365598211, and reinforced in https://github.com/googleapis/gapic-generator-ruby/pull/314#discussion_r366668620, the argument checks should use `String#include?` instead of using a regexp for performance reasons. This change does the following:
* Replace `nil` check with a check for a `String` object.
* Replace regexp match with a call to the `String#include?` method.
This change also removes some unused argument template code checking for a `#desc` value that was never implemented. The logic to check for `/` characters in all but the last argument was moved from the presenter to the template because the logic is not much simpler.
This PR is a draft PR until #314 is accepted and merged, as it dependent …
> Update resource path helper argument checks

- gapic-generator/lib/gapic/runner.rb
- gapic-generator/lib/gapic/schema/api.rb
- gapic-generator/test/gapic/schema/api_test.rb
The high level goal here is to allow configuration without a config file, since it is not currently possible to pass a custom config file from synthtool. Instead, we expand the parsing of the request parameter string to support all the data we currently have in our structured configuration—including string and symbol keys, and nested hashes. Existing usage is still supported.
The following additions/improvements were made when parsing request parameter into `protoc_options`:
* Keys are now parsed. A key that begins with a colon is turned into a symbol, otherwise a string key is used.
* Values can now contain commas and equals signs if they are backslash-escaped. (Backslashes must also be escaped.)
* Fixed a crash when a value length was a single character.
Configuration now comes directly …
> Support setting all configuration from the plugin parameter

- gapic-generator-ads/gapic-generator-ads.gemspec
- gapic-generator-ads/lib/gapic/generator/ads/version.rb
- gapic-generator-cloud/gapic-generator-cloud.gemspec
- gapic-generator-cloud/lib/gapic/generator/cloud/version.rb
- gapic-generator/gapic-generator.gemspec
- gapic-generator/lib/gapic/generator/version.rb
Two  updates to versions/dependencies:
* Rubocop needs to be a runtime dependency of the generators, because its code formatter is run as a postprocessing step when generating Ruby code. On recommendation from @blowmage, rubocop itself is a dependency of gapic-generator, while google-style is a dependency of gapic-generator-cloud.
* Clean up the gem versions so they're set to something real when we push docker images. This isn't strictly necessary, but I wanted our docker image tags to match the actual gem versions, just because.
> fix: add rubocop to runtime dependencies and set real gem versions

- gapic-generator-ads/lib/gapic/generator/ads/version.rb
- gapic-generator-cloud/bin/ruby-cloud-docker-entrypoint
- gapic-generator-cloud/lib/gapic/generator/cloud/version.rb
- gapic-generator/lib/gapic/generator/version.rb
GNU find (and `Dir.glob` as well) do not guarantee sorted results, so the ordering may not be stable across separate git pulls or unarchivings of the directory structure. This can result in changes to the ordering within generated artifacts (e.g. https://github.com/googleapis/google-cloud-ruby/pull/4749). This change tries to fix this issue by sorting input files.
Also, instead of shelling out, we use the Ruby call to glob for results, which should be more resilient against potential corner cases such as spaces in file paths.
> fix: sort input files in docker entrypoint

- gapic-generator/templates/default/helpers/presenters/field_presenter.rb
- gapic-generator/templates/default/service/test/method/_normal.erb
- shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_test.rb
Update the default assert for map fields in unary methods to be the same as other non-repeated fields
> fix: Update the default assert for map fields

- gapic-generator/templates/default/helpers/presenters/field_presenter.rb
- gapic-generator/test/gapic/presenters/field_presenter_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_test.rb
fix: set the default value for the floating point fields testing to 3.5 to avoid issues with converting between protobuf's float and Ruby's float. Previous default 3.14 after a round of back-n-forth conversion became 3.140000104904175, a difference greater than Ruby's Float:EPSILON.
> fix: set the default value for the floating point fields to 3.5

- README.md
added some basic instructions on generating Showcase with Docker. As-is right now generated Showcase will have the VERSION bug ( https://github.com/googleapis/gapic-generator-ruby/issues/325 ) so I'll make sure it is fixed before merging this.
['--ruby-cloud-gem-name' issue 323](https://github.com/googleapis/gapic-generator-ruby/issues/323) is not a blocker but it is possible to update instructions after it is fixed.
> [Docs] Add the instructions on using the Docker image to Readme

- gapic-generator/templates/default/service/client/method/def/_options_defaults.erb
- shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
- shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb
- shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/language/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
- shared/output/gapic/templates/speech/lib/google/cloud/speech/v1/speech/client.rb
This change fixes an issue where the gem's `VERSION` constant is referenced in a way that could lead to ambiguity. The example given in #325 was renaming the `google-showcase` gem to `showcase`. This caused the `VERSION` constant to be changed from `Google::Showcase::VERSION` to `Showcase::VERSION`. When the `VERSION` constant is referenced in the generated code for `Google::Showcase::V1beta1::Echo::Client`, it looked like this:
```ruby
metadata[:"x-goog-api-client"] ||= Gapic::Headers.x_goog_api_client \
lib_name: @config.lib_name, lib_version: @config.lib_version,
gapic_version: Showcase::VERSION
```
The issue is that the Ruby is walking up the current namespace to find `Showcase`. It finds it at `Google::Showcase`, but that is incorrect because it is not the top-level `Showcase`. In …
> Reference gem version using top-level constant

- gapic-generator-cloud/lib/gapic/generators/cloud_generator.rb
- shared/output/cloud/language_v1/README.md
- shared/output/cloud/language_v1/google-cloud-language-v1.gemspec
- shared/output/cloud/language_v1beta1/README.md
- shared/output/cloud/language_v1beta1/google-cloud-language-v1beta1.gemspec
- shared/output/cloud/language_v1beta2/README.md
- shared/output/cloud/language_v1beta2/google-cloud-language-v1beta2.gemspec
- shared/output/cloud/noservice/README.md
- shared/output/cloud/noservice/google-garbage-noservice.gemspec
- shared/output/cloud/secretmanager_v1beta1/README.md
- shared/output/cloud/secretmanager_v1beta1/google-cloud-secret_manager-v1beta1.gemspec
- shared/output/cloud/speech_v1/README.md
- shared/output/cloud/speech_v1/google-cloud-speech-v1.gemspec
- shared/output/cloud/vision_v1/README.md
- shared/output/cloud/vision_v1/google-cloud-vision-v1.gemspec
Yet a third approach (alternative to #344 and #347).
This simply causes the cloud generator to set the configuration field to the desired default, if not already set.
Unlike #344, this isn't a horrible hack. (Maybe it's just less horrible, but if so it's a _lot_ less horrible.)
Unlike #347, this doesn't replace/duplicate templates, and retains the ability for individual libraries to override the homepage.
> fix: set google-cloud-ruby github as the default homepage for cloud clients

- gapic-generator/templates/default/service/client/_client.erb
- gapic-generator/templates/default/service/client/method/def/_options_defaults.erb
- shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
- shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb
- shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_no_retry/client.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
We've been asked to read `quota_project_id` from credentials, and set the `X-Goog-User-Project` header accordingly if it is present. (This is for a 3LO case where billing/quota project may be different from the target/data project.)
This PR updates the microgenerator to set the appropriate header if the credentials object has an appropriately set `quota_project_id` field. This works in tandem with https://github.com/googleapis/google-auth-library-ruby/pull/254 (note that there is no hard dependency; if the credentials object field does not exist, the header will not be set.)
> feat: send x-goog-user-project header based on quota_project_id

- gapic-generator/templates/default/helpers/default_helper.rb
- gapic-generator/templates/default/service/client/_self_configure_defaults.erb
- gapic-generator/templates/default/service/client/_self_configure_retry_policy.erb
- gapic-generator/test/gapic/grpc_service_config/service_config_parsing_test.rb
- gapic-generator/test/gapic/helpers/default_helper_test.rb
- gapic-generator/test/test_helper.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb
- shared/protos/testing/grpc_service_config/grpc_service_config2.json
Create a `format_number` helper that inserts underscores for values >= 10_000, and use it for timeout and retry config settings, so the resulting code will pass rubocop.
> fix: format default config values with underscores

- gapic-generator/lib/gapic/formatting_utils.rb
- gapic-generator/test/gapic/formatting_utils_test.rb
Some protos contain documentation with braces that were passed into the generated code unescaped and as a result the generated library was failing its CI tests via yard
examples include: `{device-id}` from IOT and `{projects|folders|organizations}` from AccessApproval. 
it seems that most ascii nonword characters will fail yard when acting as a separator between words; 
I've found cases where `#` and `::` did not, unless the first word before the separator was capitalized, but even that is inconsistent, e.g. `{foo#bar}` passes but `{Foo#bar}` does not and even `{foo#bar ruby#world}` fails with 'cannot resolve link to `foo#bar`'.
Without any compelling reason to match yard's idiosyncrasies it seems better to err on the side of generated code not failing CI and so I've relaxed the …
> fix: Relax the regex around yard braces escape detection

- gapic-common/lib/gapic/call_options.rb
- gapic-common/lib/gapic/grpc/service_stub/rpc_call.rb
- gapic-common/lib/gapic/operation.rb
- gapic-generator/templates/default/service/client/method/def/_options_defaults.erb
- shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
- shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb
- shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_no_retry/client.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
In Rubies below 2.7, passing kwargs as the only hash argument is a
supported but unintentional valid way to call a function. However, in
[Ruby 2.7](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)
this is a warning, and will break in Ruby 3.0.
This commit replaces all instances of passing hashes in kwarg positions with the
`**` operator, which is valid in old rubies, as well as 2.7.
> Replace implicit kwarg hash passing with the `**` operator.

- gapic-common/lib/gapic/call_options.rb
- gapic-common/lib/gapic/operation.rb
- gapic-generator-cloud/templates/cloud/gem/gemspec.erb
- gapic-generator/templates/default/gem/gemspec.erb
- gapic-generator/templates/default/service/client/method/def/_response_normal.erb
- shared/output/cloud/language_v1/google-cloud-language-v1.gemspec
- shared/output/cloud/language_v1beta1/google-cloud-language-v1beta1.gemspec
- shared/output/cloud/language_v1beta2/google-cloud-language-v1beta2.gemspec
- shared/output/cloud/noservice/google-garbage-noservice.gemspec
- shared/output/cloud/secretmanager_v1beta1/google-cloud-secret_manager-v1beta1.gemspec
- shared/output/cloud/speech_v1/google-cloud-speech-v1.gemspec
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/google-cloud-vision-v1.gemspec
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/google-garbage.gemspec
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/grpc_service_config/testing-grpc_service_config.gemspec
- shared/output/gapic/templates/showcase/google-showcase.gemspec
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
With ads, customer ID and Developer Token are passed as call metadata,
as such, we need them to be preserved to follow on calls made through
call metadata.
This patch ensures that `Gapic::Operation` instances created in clients
that use an `OperationsClient` preserve metadata from the calls that
created them.
> Preserve call options in LROs

- gapic-generator/templates/default/helpers/presenters/gem_presenter.rb
Currently, the generator detects a dependency on the `grpc-google-iam-v1` only if a proto depends on the specific file `google/iam/v1/iam_policy.proto`. However, there are other files that should trigger the dependency, notably `google/iam/v1/policy.proto`. This is affecting the cloud asset library; without this fix, it fails to detect that it needs the `grpc-google-iam-v1` dependency, and thus the generated library fails to load.
Note: This was a long-running issue that affected the monolith as well. Currently, several libraries (including cloud asset) are fixing it with a synth hack.
> fix: trigger iam dependency for iam v1 files other than iam_policy.proto

- gapic-generator-cloud/templates/cloud/gem/rubocop.erb
- gapic-generator/templates/default/gem/rubocop.erb
- gapic-generator/templates/default/service/client/_paths.erb
- shared/output/cloud/language_v1/.rubocop.yml
- shared/output/cloud/language_v1beta1/.rubocop.yml
- shared/output/cloud/language_v1beta2/.rubocop.yml
- shared/output/cloud/noservice/.rubocop.yml
- shared/output/cloud/secretmanager_v1beta1/.rubocop.yml
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/paths.rb
- shared/output/cloud/speech_v1/.rubocop.yml
- shared/output/cloud/vision_v1/.rubocop.yml
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/paths.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/paths.rb
- shared/output/gapic/templates/garbage/.rubocop.yml
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/paths.rb
- shared/output/gapic/templates/grpc_service_config/.rubocop.yml
- shared/output/gapic/templates/showcase/.rubocop.yml
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/paths.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/paths.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/paths.rb
This lets users call `Google::Cloud::Blah::V1::MyService::Paths.my_path` without having to instantiate a client object. This is a workaround for cases where a service does not provide a particular path helper, but the helper is available on another service.
> feat: path modules extend self so helpers can be invoked on them directly

- gapic-generator-cloud/templates/cloud/wrapper_gem/rakefile.erb
since we're using the same task for both latest and master, remove extra task in https://github.com/googleapis/google-cloud-ruby/pull/5141 and use clearer task name here.
> tweak samples tasks for wrapper-gem rakefiles

- gapic-generator-cloud/Rakefile
- gapic-generator/lib/gapic/presenters/service_presenter.rb
- shared/output/cloud/secretmanager_wrapper/Rakefile
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
Previously, Operation services did not have the correct endpoint address configured because they were being generated from the generic `google.longrunning.Operations` proto, which of course doesn't have the service-specific endpoint set up. So the Operations clients were defaulting to `localhost` as the endpoint. Clearly, that won't work.
This PR fixes this by causing LRO service presenters to have a reference to the actual service they're attached to. Then the `client_endpoint` attribute uses the actual service's endpoint if that reference is present.
This PR also includes a couple of unrelated changes:
* DRY up the `image:push` and `image:release` tasks, which share almost all their logic.
* Regenerates the examples, which includes the results of #378.
> fix: Set correct endpoint for LRO services

- gapic-generator-cloud/bin/ruby-cloud-docker-entrypoint
- gapic-generator-cloud/templates/cloud/gem/rakefile.erb
- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- gapic-generator/lib/gapic/presenters/method_presenter.rb
- shared/output/cloud/secretmanager_wrapper/Rakefile
This is a grab-bag of minor changes to support generating the automl and talent libraries. Specifically:
* Disable pagination for two specific RPCs in talent v4beta1. Fixes #342 
* Provide a way to set path and namespace overrides in the docker command line. These are necessary to generate automl properly because of the unusual naming convention used.
* Boolean options in the docker command line take an argument (either `true` or `false`) because synthtool assumes all options take an argument. This also makes it possible to disable `yard_strict` (which is necessary currently for automl since the docs are malformed).
* Made `yard_strict` enabled by default in wrappers, to match the fact that it is enabled by default in gapics.
> feat: expand docker command line args, and include temporary hack for talent

- gapic-generator-cloud/templates/cloud/gem/gemspec.erb
- gapic-generator/templates/default/gem/gemspec.erb
- shared/output/cloud/secretmanager_v1beta1/google-cloud-secret_manager-v1beta1.gemspec
- shared/output/gapic/templates/garbage/google-garbage.gemspec
The common protos image embedded in the microgenerator docker releases was recently updated to include newer IAM protos with a slightly expanded interface (specifically, an extra `options` field on `GetIamPolicyRequest`). This is causing the microgenerator to generate documentation for that field, and tests that use that field, tests that were failing when run against the 0.6.9 release of the `grpc-google-iam-v1` shared protos gem. (See e.g. https://github.com/googleapis/google-cloud-ruby/pull/5356). I just built and pushed a version 0.6.10 update to the common gem with up to date protos. This PR updates the generated dependencies to call for at least that version.
The strange dependency `">= 0.6.10", "< 2.0"` is a hedge against future plans for the `grpc-google-iam-v1` library. It is a …
> feat: update shared IAM protos dependency

- gapic-generator-cloud/templates/cloud/gem/readme.erb
- gapic-generator-cloud/templates/cloud/wrapper_gem/readme.erb
- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- gapic-generator/templates/default/gem/readme.erb
- shared/output/cloud/language_v1/README.md
- shared/output/cloud/language_v1beta1/README.md
- shared/output/cloud/language_v1beta2/README.md
- shared/output/cloud/noservice/README.md
- shared/output/cloud/secretmanager_v1beta1/README.md
- shared/output/cloud/secretmanager_wrapper/README.md
- shared/output/cloud/speech_v1/README.md
- shared/output/cloud/vision_v1/README.md
- shared/output/gapic/templates/garbage/README.md
- shared/output/gapic/templates/grpc_service_config/README.md
- shared/output/gapic/templates/showcase/README.md
Fixes #375.
This provides an expanded generated readme that includes a simple quickstart showing which file to require and generally how to create a client using one of the versioned gems.
It also includes an even more expanded readme for cloud clients that includes before-you-begin info on setting up projects, billing, auth, etc., as well as providing links to documentation.
> feat: Expanded readme for normal default clients and cloud clients

- gapic-generator/lib/gapic/presenters/field_presenter.rb
- gapic-generator/lib/gapic/presenters/method_presenter.rb
- gapic-generator/templates/default/service/client/method/docs/_request_normal.erb
- gapic-generator/templates/default/service/client/method/docs/_request_streaming.erb
- shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
- shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb
- shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_no_retry/client.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
This is a general cleanup of the documentation for method calling conventions. Specifically:
* In the "request object" overload, added a brief overview saying you can pass request proto objects or equivalent hashes.
* In the "request object" overload, the docs for the `request` parameter were a repeat of the overall method docs. This was not useful. Replaced it with a general description of a request object.
* In the "keyword arguments" overload, added a brief overview. Also noted here that at least one keyword argument is required, and that if a user wants to pass no arguments, they should pass an empty hash as a request object. (Fixes #390)
* Removed an extra newline that appeared in the comments between the params section and the yields section.
* Overall, replaced `|` with `,` as the …
> feat: improve method docs

- gapic-generator-cloud/templates/cloud/gem/rubocop.erb
- gapic-generator/templates/default/gem/rubocop.erb
- shared/output/cloud/language_v1/.rubocop.yml
- shared/output/cloud/language_v1beta1/.rubocop.yml
- shared/output/cloud/language_v1beta2/.rubocop.yml
- shared/output/cloud/noservice/.rubocop.yml
- shared/output/cloud/secretmanager_v1beta1/.rubocop.yml
- shared/output/cloud/speech_v1/.rubocop.yml
- shared/output/cloud/vision_v1/.rubocop.yml
- shared/output/gapic/templates/garbage/.rubocop.yml
- shared/output/gapic/templates/grpc_service_config/.rubocop.yml
- shared/output/gapic/templates/showcase/.rubocop.yml
DLP V2 generates lots of path helpers, causing `paths.rb` to violate `Metrics/ModuleLength`. Disable this metric for generated files.
> fix: Disable module length metric

- gapic-generator/lib/gapic/presenters/resource_presenter.rb
- gapic-generator/templates/default/service/client/_resource.erb
Currently, the resource presenter asserts that resource patterns follow its prescribed format and raises an exception if not. However, there are resources in the wild with legal patterns that do not conform (e.g. monitoring v3). Hence, we loosen the check, and instead just omit those patterns from the presenter (meaning they do not participate in the path generation options provided by the path helper). Along with this, we need to handle the case that a resource has _no_ conforming patterns.
> fix: Loosen resource pattern checks

- gapic-generator/templates/default/service/client/_client.erb
- gapic-generator/templates/default/service/test/client.erb
- gapic-generator/templates/default/service/test/client_operations.erb
- gapic-generator/templates/default/service/test/method/_configure.erb
- shared/output/cloud/language_v1/test/google/cloud/language/v1/language_service_test.rb
- shared/output/cloud/language_v1beta1/test/google/cloud/language/v1beta1/language_service_test.rb
- shared/output/cloud/language_v1beta2/test/google/cloud/language/v1beta2/language_service_test.rb
- shared/output/cloud/secretmanager_v1beta1/test/google/cloud/secret_manager/v1beta1/secret_manager_service_test.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/test/google/cloud/speech/v1/speech_operations_test.rb
- shared/output/cloud/speech_v1/test/google/cloud/speech/v1/speech_test.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/image_annotator_operations_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/image_annotator_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/product_search_operations_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/product_search_test.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_operations_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_test.rb
- shared/output/gapic/templates/grpc_service_config/test/testing/grpc_service_config/service_no_retry_test.rb
- shared/output/gapic/templates/grpc_service_config/test/testing/grpc_service_config/service_with_retries_test.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/echo_operations_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/echo_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/identity_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/messaging_operations_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/messaging_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/testing_test.rb
Several small items that have come up over the past week. I want to get these cleaned out before the next, larger PR related to "common" services.
Specifics:
* If the main client has a custom endpoint, the LRO client didn't inherit it. Fixed.
* There isn't currently a way to call `list_operations` because the LRO client object isn't accessible directly. Added an accessor.
* Generate tests for the `configure` method and the operations client accessor.
> feat: Various enhancements to LRO clients.

- gapic-generator/templates/default/service/client/_client.erb
- gapic-generator/templates/default/service/client/_config.erb
- shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
- shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb
- shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/iam_policy/client.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_no_retry/client.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
Timeouts in gapic-common are specified in seconds, not milliseconds. This PR fixes the documentation and examples in generated clients accordingly.
> fix: Timeouts are in seconds rather than milliseconds

- gapic-generator-cloud/templates/cloud/wrapper_gem/gemfile.erb
- gapic-generator-cloud/templates/cloud/wrapper_gem/gemspec.erb
- shared/output/cloud/secretmanager_wrapper/Gemfile
- shared/output/cloud/secretmanager_wrapper/google-cloud-secret_manager.gemspec
The pinning is unnecessary because we don't use minitest/spec.
> feat: Unpin minitest in generated wrappers

- gapic-generator/lib/gapic/generators/default_generator.rb
- gapic-generator/lib/gapic/presenters/resource_presenter.rb
- gapic-generator/lib/gapic/presenters/service_presenter.rb
- gapic-generator/templates/default/service/client/resource/_multi.erb
- gapic-generator/templates/default/service/client/resource/_single.erb
- gapic-generator/templates/default/service/test/_resource.erb
- gapic-generator/templates/default/service/test/client_paths.erb
- gapic-generator/test/gapic/presenters/service/garbage_iam_test.rb
- shared/output/cloud/secretmanager_v1beta1/test/google/cloud/secret_manager/v1beta1/secret_manager_service_paths_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/image_annotator_paths_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/product_search_paths_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_paths_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/resource_names_paths_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/identity_paths_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/messaging_paths_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/testing_paths_test.rb
Add generated tests for resource path helpers.
The main purpose of this is actually to address item 3 in #414 because if a collision occurs, the tests will fail.
ResourcePresenter has been refactored as part of this. The "pattern" object, which was originally an OpenStruct, has been given its own class so that we can define some convenience presenter methods on it. Not only does this support generating the path tests, but it simplified the templates for the paths module itself.
Also fixed the name of a test class that was colliding with another test class and causing warnings (and resulting in some tests not running.)
> feat: Generate tests for resource path helpers

- gapic-generator-cloud/templates/cloud/wrapper_gem/gemfile.erb
- gapic-generator/templates/default/gem/gemfile.erb
- shared/output/cloud/language_v1/Gemfile
- shared/output/cloud/language_v1beta1/Gemfile
- shared/output/cloud/language_v1beta2/Gemfile
- shared/output/cloud/noservice/Gemfile
- shared/output/cloud/secretmanager_v1beta1/Gemfile
- shared/output/cloud/secretmanager_wrapper/Gemfile
- shared/output/cloud/speech_v1/Gemfile
- shared/output/cloud/vision_v1/Gemfile
- shared/output/gapic/templates/garbage/Gemfile
- shared/output/gapic/templates/grpc_service_config/Gemfile
- shared/output/gapic/templates/showcase/Gemfile
Version 3.12.0 of the `google-protobuf` gem will not install on Ruby 2.4. This change updates the generated Gemfiles to pin `google-protobuf` to 3.11.x on older Rubies.
> fix: Pin protobuf dependency on old rubies

- gapic-generator-cloud/lib/gapic/presenters/wrapper_gem_presenter.rb
Remove `AUTHENTICATION.md` from the list of files in the gemspec of a generic (i.e. non-Google-specific) wrapper. Such wrappers have no `AUTHENTICATION.md` because it is a Google-specific file.
This is necessary to fix the `grafeas` gem.
> fix: Remove auth file from gemspec for generic wrappers

- gapic-generator-ads/Dockerfile
- gapic-generator-ads/Rakefile
merging Penelope's improvements
CR #472
CR https://github.com/googleapis/gapic-generator-ruby/pull/472#issuecomment-648391338
> feat: copy ads protos from latest and don't use cache when invoking build from Rakefile

- gapic-generator/templates/default/service/test/method/_setup.erb
- shared/output/cloud/language_v1/test/google/cloud/language/v1/language_service_test.rb
- shared/output/cloud/language_v1beta1/test/google/cloud/language/v1beta1/language_service_test.rb
- shared/output/cloud/language_v1beta2/test/google/cloud/language/v1beta2/language_service_test.rb
- shared/output/cloud/secretmanager_v1beta1/test/google/cloud/secret_manager/v1beta1/secret_manager_service_test.rb
- shared/output/cloud/speech_v1/test/google/cloud/speech/v1/speech_operations_test.rb
- shared/output/cloud/speech_v1/test/google/cloud/speech/v1/speech_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/image_annotator_operations_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/image_annotator_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/product_search_operations_test.rb
- shared/output/cloud/vision_v1/test/google/cloud/vision/v1/product_search_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_operations_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/garbage_service_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/iam_policy_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/really_renamed_service_test.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/resource_names_test.rb
- shared/output/gapic/templates/grpc_service_config/test/testing/grpc_service_config/service_no_retry_test.rb
- shared/output/gapic/templates/grpc_service_config/test/testing/grpc_service_config/service_with_retries_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/echo_operations_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/echo_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/identity_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/messaging_operations_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/messaging_test.rb
- shared/output/gapic/templates/showcase/test/google/showcase/v1beta1/testing_test.rb
Eliminates a warning that is appearing in our CI runs on Ruby 2.7.
> fix: Eliminate Ruby 2.7 keyword arguments warning in generated tests

- gapic-generator/lib/gapic/presenters/service_presenter.rb
currently if a service has no options defined at all, the client_scopes for the ServicePresenter will be nil (absent a default config or a delegate provided). This leads to a nil exception later in the generation process. This change rectifies
> fix: fix an issue when generating a service with no options would fail

- gapic-generator/lib/gapic/file_formatter.rb
when ran from a sandbox environment (bazel) it helps to not try to leave side-effects and it does not seem to matter either way in other cases
> fix: make rubocop run without caching for file formatting

- gapic-generator-cloud/bin/protoc-gen-ruby_cloud
need to have this when executing the entrypoint from e.g. bazel
> Fix: add the loading path to the gapic-generator-cloud

- gapic-generator-ads/bin/protoc-gen-ruby_ads
need to have this when executing the entrypoint from e.g. bazel
> Fix: add the loading path to the gapic-generator-adc

- gapic-generator-cloud/templates/cloud/gem/authentication.erb
- gapic-generator-cloud/templates/cloud/gem/rakefile.erb
- gapic-generator-cloud/templates/cloud/gem/readme.erb
- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- gapic-generator/lib/gapic/schema/api.rb
- gapic-generator/templates/default/gem/readme.erb
- gapic-generator/test/gapic/presenters/gem_presenter_test.rb
- gapic-generator/test/test_helper.rb
Fix two issues:
* Examples in auth, rakefile, and readme should pick a non-common service.
* We'd like to emit a warning if the `common_services` configuration references services that don't exist (in case we misspelled them).
Also started a test helper class `FakeRequest` that lets you create a "fake" request as input to the generator. This should be more useful as a test fixture than `FakeApi`, and indeed the eventual goal is to replace `FakeApi` with a real `Schema::Api` that uses `FakeRequest` as an input. The tests for these two fixes use `FakeRequest`.
> fix: Use a reasonable service for examples

- shared/input/proto_input
- shared/output/cloud/expected_output
- shared/output/gapic/expected_output
> fix: remove circular symlinks that serve no purpose

- gapic-generator-cloud/templates/cloud/gem/rubocop.erb
- gapic-generator-cloud/templates/cloud/wrapper_gem/rubocop.erb
- gapic-generator/templates/default/gem/rubocop.erb
- shared/output/cloud/language_v1/.rubocop.yml
- shared/output/cloud/language_v1beta1/.rubocop.yml
- shared/output/cloud/language_v1beta2/.rubocop.yml
- shared/output/cloud/noservice/.rubocop.yml
- shared/output/cloud/secretmanager_v1beta1/.rubocop.yml
- shared/output/cloud/secretmanager_wrapper/.rubocop.yml
- shared/output/cloud/speech_v1/.rubocop.yml
- shared/output/cloud/vision_v1/.rubocop.yml
- shared/output/gapic/templates/garbage/.rubocop.yml
- shared/output/gapic/templates/grpc_service_config/.rubocop.yml
- shared/output/gapic/templates/showcase/.rubocop.yml
Rubocop disallows non-ascii characters in comments by default (enforcing a Ruby style rule that comments should be in English). [AIP 192](https://google.aip.dev/192), which governs documentation, recommends that comments should be in American English but does not insist on it, and there are cases (e.g. examples) when it makes sense for non-ascii characters to appear. (This is already affecting at least one existing service.) So we're going to disable the Style/AsciiComments cop.
> fix: Disable AsciiComments style rule

- .github/workflows/ci.yml
- Rakefile
- shared/.gitignore
GitHub Actions config that replicates the current CircleCI config (with the difference that showcase is being updated from 0.5 to 0.12). This will let us turn down CircleCI for this repo.
> chore: Configure GitHub Actions

- gapic-generator-cloud/templates/cloud/wrapper_gem/_main.erb
- gapic-generator/templates/default/service/client/_config.erb
- shared/output/ads/googleads/lib/google/ads/google_ads/v1/services/campaign_service/client.rb
- shared/output/cloud/language_v1/lib/google/cloud/language/v1/language_service/client.rb
- shared/output/cloud/language_v1beta1/lib/google/cloud/language/v1beta1/language_service/client.rb
- shared/output/cloud/language_v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
- shared/output/cloud/secretmanager_v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
- shared/output/cloud/secretmanager_wrapper/lib/google/cloud/secret_manager.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/client.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/iam_policy/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/really_renamed_service/client.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/resource_names/client.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_no_retry/client.rb
- shared/output/gapic/templates/grpc_service_config/lib/testing/grpc_service_config/service_with_retries/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/client.rb
closes https://github.com/googleapis/gapic-generator-ruby/issues/522
> fix: the documentation for the timeout in the templates (change milliseconds and fix docs)

- gapic-generator-cloud/lib/gapic/presenters/cloud_gem_presenter.rb
- gapic-generator-cloud/lib/gapic/presenters/wrapper_gem_presenter.rb
- gapic-generator-cloud/templates/cloud/gem/readme.erb
- gapic-generator-cloud/templates/cloud/wrapper_gem/readme.erb
- shared/output/cloud/language_v1/README.md
- shared/output/cloud/language_v1/google-cloud-language-v1.gemspec
- shared/output/cloud/language_v1beta1/README.md
- shared/output/cloud/language_v1beta1/google-cloud-language-v1beta1.gemspec
- shared/output/cloud/language_v1beta2/README.md
- shared/output/cloud/language_v1beta2/google-cloud-language-v1beta2.gemspec
- shared/output/cloud/secretmanager_v1beta1/README.md
- shared/output/cloud/secretmanager_v1beta1/google-cloud-secret_manager-v1beta1.gemspec
- shared/output/cloud/secretmanager_wrapper/README.md
- shared/output/cloud/speech_v1/README.md
- shared/output/cloud/speech_v1/google-cloud-speech-v1.gemspec
- shared/output/cloud/vision_v1/README.md
- shared/output/cloud/vision_v1/google-cloud-vision-v1.gemspec
This adds content to gem descriptions that tries to clarify the difference between versioned and wrapper clients, and directs users to install the wrapper. Specifically:
* Updates the description field in the gemspec for versioned clients, directing users to consider installing the wrapper instead.
* Adds a section to every generated readme entitled "Which client should I use?" that details the difference between versioned and wrapper clients.
* Adds a brief note at the top of the readme for versioned clients, directing users to consider installing the wrapper.
> feat: Update generated readmes to cover versioned vs wrapper clients

- bazel_example/WORKSPACE.bazel
- bazel_example/gapic-generator/BUILD.bazel
noncloud example can benefit from having a real library in it, now that showcase Bazel bindings are there
> feat: add showcase library to the noncloud examples

- gapic-generator-ads/CHANGELOG.md
- gapic-generator-ads/Gemfile.lock
- gapic-generator-ads/gapic-generator-ads.gemspec
- gapic-generator-ads/lib/gapic/generator/ads/version.rb
- gapic-generator-cloud/CHANGELOG.md
- gapic-generator-cloud/Gemfile.lock
- gapic-generator-cloud/gapic-generator-cloud.gemspec
- gapic-generator-cloud/lib/gapic/generator/cloud/version.rb
- gapic-generator/CHANGELOG.md
- gapic-generator/Gemfile.lock
- gapic-generator/lib/gapic/generator/version.rb
This release updates to google-style 1.25 and drops Ruby 2.4 support for generated libraries.
> chore: Release v0.7.0

- gapic-common/CHANGELOG.md
- gapic-common/lib/gapic/common/version.rb
- gapic-common/lib/gapic/rest/client_stub.rb
in recognition that POST requests with empty body are uncommon but not incorrect, and we generate them for REGAPIC
( https://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0273.html )
> fix: provide a default value for the 'body' param in the post method

- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- shared/output/cloud/compute_small/AUTHENTICATION.md
- shared/output/cloud/compute_small/Rakefile
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/addresses/credentials.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/networks/credentials.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_instance_group_managers/credentials.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_operations/credentials.rb
Handles the case where `--env-prefix=` is not provided and the proto namespace includes a version.
> fix: Fix default env_prefix computation to avoid the version part of the namespace

- gapic-generator-cloud/lib/gapic/presenters/cloud_gem_presenter.rb
- gapic-generator-cloud/templates/cloud/gem/repo-metadata.erb
- gapic-generator/lib/gapic/schema/api.rb
- shared/output/cloud/compute_small/.repo-metadata.json
- shared/output/cloud/language_v1/.repo-metadata.json
- shared/output/cloud/language_v1beta1/.repo-metadata.json
- shared/output/cloud/language_v1beta2/.repo-metadata.json
- shared/output/cloud/noservice/.repo-metadata.json
- shared/output/cloud/secretmanager_v1beta1/.repo-metadata.json
- shared/output/cloud/secretmanager_wrapper/.repo-metadata.json
- shared/output/cloud/speech_v1/.repo-metadata.json
- shared/output/cloud/vision_v1/.repo-metadata.json
This will make it easier to generate the synth files for wrapper libraries, by ensuring that all the original gapic library's generator_args are present in one form or another in the repo-metadata file.
Note: depends on #607 . Tests will not pass until that PR is merged.
> feat: Save generation args in repo metadata

- gapic-generator-cloud/lib/gapic/presenters/wrapper_gem_presenter.rb
- shared/output/cloud/secretmanager_wrapper/google-cloud-secret_manager.gemspec
Currently most of our generated clients have versions in the 0.x range. This needs to change for GA services (e.g. services with versions like "v1" as opposed to "v1beta1"). We want to bump those library versions to 1.0 at some point soon. However, that could lead to diamond dependency issues with wrapper gems that still depend on `~> 0.x`. Here we implement the strategy we've been using for other libraries that we want to bump from 0.x to 1.0: Updating the dependencies so that they are of the form `">= 0.x", "< 2.a"` so they support both 0.x and 1.x. We can do this because in most cases, the 0.x to 1.0 version bump is not really a semver-major (backward incompatible) bump, but merely a promotion of the version from "prerelease" to "GA".
> fix: Wrapper gem dependencies on pre-ga versioned gems also allow 1.x versions

- gapic-generator-cloud/Rakefile
- gapic-generator/lib/gapic/presenters/resource_presenter.rb
- gapic-generator/lib/gapic/presenters/service_presenter.rb
- gapic-generator/templates/default/service/client/_paths.erb
- gapic-generator/templates/default/service/test/client_paths.erb
- gapic-generator/test/gapic/presenters/service_presenter_test.rb
- gapic-generator/test/test_helper.rb
- shared/Rakefile
- shared/config/document_ai_v1beta3.yml
Prevents "duplicate" resources (i.e. resources with the same name but potentially different namespaces) from producing "duplicate" path helpers (e.g. https://github.com/googleapis/google-cloud-ruby/pull/12787)
> fix: Prevent duplicate path helper methods

- bazel_example/WORKSPACE.bazel
- bazel_example/diregapic/BUILD.bazel
- rules_ruby_gapic/repositories.bzl
- some references to other repos were not updated when cleaning up monolith dependencies
- fixed duplication in rules_ruby_gapic
- updated compute example to produce more realistic diregapic library
> fix: bazel examples not working properly

- gapic-generator-cloud/Rakefile
- gapic-generator-cloud/templates/cloud/gem/authentication.erb
- gapic-generator-cloud/templates/cloud/gem/readme.erb
- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- gapic-generator/lib/gapic/presenters/method_rest_presenter.rb
- gapic-generator/lib/gapic/presenters/service_presenter.rb
- gapic-generator/lib/gapic/presenters/service_rest_presenter.rb
- shared/Rakefile
- shared/config/document_ai_v1beta3.yml
- shared/output/cloud/compute_small/AUTHENTICATION.md
- shared/output/cloud/compute_small/README.md
- shared/output/cloud/noservice/README.md
> fix: Show REST-specific examples in markdown docs for REST-only clients

- gapic-generator/templates/default/service/rest/client/_config.erb
- gapic-generator/templates/default/service/rest/client/method/def/_options_defaults.erb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/addresses/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/networks/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_instance_group_managers/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_operations/rest/client.rb
feat: enable per-rpc config for REST libraries
feat: enable metadata configuration (client-level and per-rpc) for REST libraries
> feat: enable per-rpc config for REST libraries

- .github/renovate.json
- bazel_example/WORKSPACE.bazel
chore: update bazel examples workspace
chore: add renovate config excluding test output and bazel_examples
There is not much point in updating bazel_examples until they are part of the CI
> chore: update bazel_examples, add renovate.config

- gapic-generator-ads/Gemfile.lock
- gapic-generator-cloud/Gemfile.lock
- gapic-generator-cloud/templates/cloud/gem/rubocop.erb
- gapic-generator/Gemfile.lock
- shared/output/cloud/compute_small/.rubocop.yml
- shared/output/cloud/language_v1/.rubocop.yml
- shared/output/cloud/language_v1beta1/.rubocop.yml
- shared/output/cloud/language_v1beta2/.rubocop.yml
- shared/output/cloud/secretmanager_v1beta1/.rubocop.yml
- shared/output/cloud/speech_v1/.rubocop.yml
- shared/output/cloud/vision_v1/.rubocop.yml
Prevents, e.g. https://github.com/googleapis/google-cloud-ruby/pull/13607/files
> fix: Disable rubocop for sample tests in generated versioned libraries

- gapic-generator-ads/CHANGELOG.md
- gapic-generator-ads/Gemfile.lock
- gapic-generator-ads/lib/gapic/generator/ads/version.rb
- gapic-generator-cloud/CHANGELOG.md
- gapic-generator-cloud/Gemfile.lock
- gapic-generator-cloud/lib/gapic/generator/cloud/version.rb
- gapic-generator/CHANGELOG.md
- gapic-generator/Gemfile.lock
- gapic-generator/lib/gapic/generator/version.rb
I'm releasing the current set of changes (_not_ including the global enabling of snippet-gen) along with the results of running them on google-cloud-ruby (https://github.com/googleapis/google-cloud-ruby/pull/14492). This is to give us a clean slate for the next set of updates which will be more disruptive.
> chore: Release version 0.10.2

- gapic-generator/lib/gapic/model/method/http_annotation.rb
- gapic-generator/test/gapic/path_pattern/regex_path_pattern_test.rb
- gapic-generator/test/gapic/routing_headers/explicit_routing_headers_input_match_test.rb
this adds tests for the explicit routing headers that contain:
* references to the sub-field, e.g. `{ field: "sub.name", path_template: "subs/{sub_name}" }`
* key names that have a dot (`.`) in it, e.g. `{ field: "app_profile_id", path_template: "{legacy.routing_id=**}" }`
fixes: #730
> Chore: test for subfields and header keys containing a dot in explicit routing headers

- gapic-generator/lib/gapic/model/mixins.rb
- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- gapic-generator/lib/gapic/presenters/package_presenter.rb
- rules_ruby_gapic/private/ruby_gapic_library_internal.bzl
- rules_ruby_gapic/ruby_gapic.bzl
- shared/output/gapic/templates/testing/testing.gemspec
* Mixin dependencies were `"~> 0.1"` which precludes 1.x. Changed to `[">= 0.0", "< 2.a"]` to conform to how we're doing dependencies on other libraries that we intend to promote to 1.0.
* Mixins currently require passing in a service-yaml file, but the `service_yaml` field in the bazel config wasn't implemented as it is in other languages. This made it difficult to specify the service yaml path because it needs to be included as an argument and added implicitly to the depset. Fixed (I think).
> Several fixes for mixins (rebase-merge to get individual commit messages)

- gapic-common/lib/gapic/headers.rb
- gapic-common/lib/gapic/rest/client_stub.rb
3 fixes that combined/rest libraries need in gapic-common
1. Combined libraries will load `grpc/error` (but not `grpc/version`) via `require 'gapic/common'`. Ideally the load of `grpc/error` should be moved to `gapic/grpc` but full impact of that move should be evaluated separately.
Meanwhile, having `::GRPC` but not `::GRPC::Error` will lead to exception in `gapic/headers.rb`. This fixes.
2. Passing a frozen string as an endpoint can happen in testing, and `gsub!` will fail. This does not need combined to happen, so in theory it affects Compute right now, but no one acceptance-tests compute against a local endpoint.
3. Similarly, passing a symbol as a credential in testing (`:this_channel_is_insecure`) should mean "don't try to do auth", just as it is in GRPC. This implements by …
> fix: small fixes for combined libraries and testing

- gapic-generator/templates/default/service/client/_operations.erb
- shared/output/cloud/compute_small_wrapper/lib/google/cloud/compute.rb
- shared/output/cloud/speech_v1/lib/google/cloud/speech/v1/speech/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/operations.rb
- shared/output/gapic/templates/testing/lib/testing/nonstandard_lro_grpc/all_subclients_consumer/operations.rb
Fix the internal Operations clients referencing a nonexistent private field. See https://github.com/googleapis/google-cloud-ruby/pull/18340 for example of how things break.
> fix: LRO-wrapped methods of the internal Operations client not working

- .github/workflows/ci-common.yml
- gapic-common/README.md
- gapic-common/gapic-common.gemspec
- gapic-common/lib/gapic/generic_lro/operation.rb
- gapic-common/lib/gapic/operation.rb
- gapic-common/lib/gapic/paged_enumerable.rb
- gapic-common/lib/gapic/protobuf.rb
- gapic-common/lib/gapic/rest/client_stub.rb
- gapic-common/lib/gapic/rest/grpc_transcoder.rb
- gapic-common/test/gapic/config/errors_test.rb
- gapic-common/test/gapic/protobuf/coerce_test.rb
- gapic-common/test/gapic/protobuf/time_test.rb
This PR adds support for both Faraday `~> 1.9` and `~> 2.0`, to avoid causing diamond dependency issues for clients. Note that since we use the request-retry middleware, we require a version of Faraday (`>= 1.9`) that uses the faraday-retry gem. If the user is using Faraday 1.x, Faraday itself will depend on faraday-retry 1.x. If the user is using Faraday 2.x, gapic-common will bring in faraday-retry 2.x as a dependency. Hence, the "permissive" faraday-retry dependency that allows both 1.x and 2.x.
Also includes the following:
* feat(gapic-common): Require at least Ruby 2.6
* fix(gapic-common): Fix some Ruby 3.0 keyword argument usage errors
* fix(gapic-common): Fix precision issues in protobuf timestamp conversion
* chore: Add a CI job for gapic-common CI against a matrix of Ruby …
> feat(gapic-common): Support faraday 2.0

- gapic-generator/lib/gapic/formatting_utils.rb
- gapic-generator/test/gapic/formatting_utils_test.rb
Apparently both AutoML and VMMigration depend on namespace overrides to update the capitalization of the service name.
> fix: Apply both namespace and service overrides to service names in yard links

- .github/workflows/ci-common.yml
- gapic-common/lib/gapic/call_options.rb
- gapic-common/lib/gapic/call_options/retry_policy.rb
- gapic-common/test/gapic/call_options/settings_test.rb
Adds:
* Correct equality checking for `Gapic::CallOptions` and `Gapic::CallOptions::RetryPolicy`
* Corresponding hashcode computation
* `merge` method for `Gapic::CallOptions`
These are necessary for CallOptions to be used successfully in the mocks for the spanner client tests. We've had a bit of a challenge getting those tests working again with the changes to minitest 5.16, and my current solution is for the tests to use CallOptions objects rather than hashes to pass call options. This means CallOptions objects need proper equality checking so the mocks can recognize them. There are also a few tests that are calling `Hash#merge` on call options hashes, so this replicates that functionality on the CallOptions class.
> feat: Add CallOptions#merge and CallOptions equality checking

- gapic-common/lib/gapic/generic_lro/operation.rb
- gapic-common/lib/gapic/rest/grpc_transcoder.rb
- gapic-common/test/gapic/generic_lro_test.rb
- gapic-common/test/gapic/rest/grpc_transcoder_test.rb
fix: error code of 0 is not an error for Generic LRO. Compute returns 0 in the error code field on success.
fix: body template field can be nil. This theoretically relaxes transcoding but there are no/should not be cases when somebody would use the nill-ness of a body field as a binding selector.
> fix: error code of 0 is not an error, body template field can be nil

- gapic-common/lib/gapic/rest/client_stub.rb
- gapic-common/test/gapic/rest/client_stub_test.rb
This is part of the numeric enums work. It adds a feature to Gapic::Rest::ClientStub that lets you configure it as a service that supports the `enum-encoding=int` signal (see internal document go/cloudsdk-esf-json-enum-number). This will be released as a minor version update for gapic-common. (In a separate PR, the generator will be updated to pass the appropriate value to the ClientStub constructor in the ServiceStub template.)
This also:
* Adds tests for ClientStub
* Fixes exceptions if `nil` or a hash are passed in as the `options:` argument to `ClientStub#make_http_request`. These don't happen in the current generated compute client because the generated client class ensures that a true `Gapic::CallOptions` object is always passed for this argument. However, in the generated low-level …
> feat(gapic-common): Support numeric_enums in the ClientStub

- gapic-common/lib/gapic/call_options/retry_policy.rb
- gapic-common/lib/gapic/grpc.rb
- gapic-common/lib/gapic/grpc/errors.rb
- gapic-common/lib/gapic/grpc/service_stub.rb
- gapic-common/lib/gapic/grpc/service_stub/rpc_call.rb
- gapic-common/lib/gapic/headers.rb
- gapic-common/lib/gapic/paged_enumerable.rb
- gapic-common/test/gapic/grpc/rpc_call/raise_test.rb
- gapic-common/test/gapic/grpc/rpc_call/retry/raise_test.rb
- Reclassifies `::GRPC::Unavailable` errors that contain `Signet::AuthorizationError` into `Gapic::GRPC::AuthorizationError` which is derived from `::GRPC::Unauthenticated`
- If an exception led to a retry, and then a deadline was exceeded, when `::GRPC::DeadlineExceeded` was thrown, it gets wrapped into the `Gapic::GRPC::DeadlineExceededError` which inherits from `::GRPC::DeadlineExceeded` but contains additional information about the retried exception.
Related to and will fix: https://github.com/googleads/google-ads-ruby/issues/246.
Internal re: go/cloudclibs-ruby-unavailable-auth
> feat: rewrap certain grpc errors

- gapic-common/lib/gapic/rest/threaded_enumerator.rb
Fixes a bug in the threaded enumerator where out_q indefinitely waits for nil (terminating) value.
> fix: deadlock fix

- gapic-common/lib/gapic/rest/faraday_middleware.rb
also take Faraday middleware `@private`.
fixes: https://github.com/googleapis/gapic-generator-ruby/issues/840
> feat: add support for different types of credentials to REST

- gapic-generator/templates/default/service/rest/client/_client.erb
- gapic-generator/templates/default/service/rest/client/_config.erb
- gapic-generator/templates/default/service/rest/client/_operations.erb
- gapic-generator/templates/default/service/rest/client/method/def/_options_defaults.erb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/addresses/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/global_operations/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/networks/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_instance_group_managers/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_operations/rest/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/compliance/rest/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/identity/rest/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/rest/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/messaging/rest/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/testing/rest/client.rb
* Add quota project to REGAPIC templates
* migrate minor improvements e.g. signed JWTs and `#@example` to REGAPIC templates
ref: https://github.com/googleapis/gapic-generator-ruby/issues/841 1/3
> feat: add quota project and misc to REGAPIC templates

- gapic-common/lib/gapic/call_options/retry_policy.rb
This happens because GRPC does not actually get loaded unless you're coming from the GRPC stub classes. For a REST call, we need to check whether the GRPC namespace exists before attempting to test against its contents.
> fix: Fixed uninitialized constant when checking retry policy for a REST call

- gapic-generator/lib/gapic/presenters/service_rest_presenter.rb
- gapic-generator/templates/default/service/rest/client/_client.erb
fix: avoid creating rest default configuration for the methods that don't have rest bindings
> fix: avoid creating rest default configuration for non-rest methods

- rules_ruby_gapic/private/ruby_gapic_library_internal.bzl
- rules_ruby_gapic/ruby_gapic.bzl
Assumes that the format is `"grpc"`, `"rest"`, or `"grpc+rest"`. Translates to the ruby generator representation which uses semicolon to delimit array elements.
> feat: Recognize transport argument for bazel jobs

- gapic-generator-cloud/templates/cloud/wrapper_gem/client_test.erb
- shared/output/cloud/compute_small_wrapper/test/google/cloud/compute/client_test.rb
- shared/output/cloud/language_wrapper/test/google/cloud/language/client_test.rb
Using "chore" because this is a fix to a previous PR that hasn't yet been released, so we don't need an extra changelog entry.
> chore: Fix requires in generated wrapper tests

- gapic-generator/lib/gapic/generators/default_generator.rb
The code (currently) applies only to REST, and it's required from rest.rb so it's dead code if that's not present.
> fix: Don't generate bindings_override.rb unless REST transport is active

- gapic-generator/lib/gapic/generators/default_generator.rb
fixes [887](https://github.com/googleapis/gapic-generator-ruby/issues/887)
> fix: fail when rest transport specified but no HTTP bindings

- gapic-generator-cloud/Rakefile
NB: will work after rebasing on https://github.com/googleapis/gapic-generator-ruby/pull/896
> fix: remove a deprecated method usage that new Ruby does not like

- gapic-generator/lib/gapic/model/mixins.rb
Do not release until google-cloud-location and google-iam-v1 0.3 are released, of course.
> feat: Bump mixin minimum version to 0.3

- gapic-generator/lib/gapic/presenters/snippet/client_call_presenter.rb
- gapic-generator/lib/gapic/presenters/snippet/client_initialization_presenter.rb
- gapic-generator/lib/gapic/presenters/snippet/expression_presenter.rb
- gapic-generator/lib/gapic/presenters/snippet/request_initialization_presenters.rb
- gapic-generator/lib/gapic/presenters/snippet/response_handling_presenters.rb
- gapic-generator/lib/gapic/presenters/snippet/statement_presenter.rb
- gapic-generator/lib/gapic/presenters/snippet/type_presenter.rb
- gapic-generator/test/gapic/presenters/snippet/client_call_presenter_test.rb
- gapic-generator/test/gapic/presenters/snippet/client_initialization_presenter_test.rb
- gapic-generator/test/gapic/presenters/snippet/expression_presenter_test.rb
- gapic-generator/test/gapic/presenters/snippet/request_initialization_presenter_test.rb
- gapic-generator/test/gapic/presenters/snippet/response_handling_presenter_test.rb
- gapic-generator/test/gapic/presenters/snippet/snippet_test_helper.rb
- gapic-generator/test/gapic/presenters/snippet/statement_presenter_test.rb
- gapic-generator/test/gapic/presenters/snippet/type_presenter_test.rb
This is the "core" of the Ruby snippetgen phase2 implementation, a series of classes that interpret snippetgen configuration and generate snippets of code.
Each class takes as input a proto object, and the corresponding JSON source, and generally provides a `render` and/or `render_lines` method to get the code rendering. The JSON is needed, unfortunately, because the Ruby generator currently uses a third-party proto implementation that doesn't fully understand oneof, and we need the original JSON to fully disambiguate which choice is made.
In this PR, these classes are unit tested, but the main pipeline does not use them yet.
Note: until #890 is merged, the first 4 commits are part of #890 and should be ignored.
The remaining commits implement the following, in order. Each commit is …
> feat: Implement core snippetgen phase2 presenters

- gapic-generator-cloud/lib/gapic/presenters/cloud_gem_presenter.rb
- gapic-generator/lib/gapic/model/api_metadata.rb
- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- gapic-generator/lib/gapic/presenters/snippet_presenter.rb
- gapic-generator/lib/gapic/schema/api.rb
- gapic-generator/lib/gapic/schema/service_config_parser.rb
- gapic-generator/test/gapic/presenters/gem/showcase_test.rb
- gapic-generator/test/gapic/schema/service_config_parser_test.rb
- shared/output/cloud/vision_v1/.repo-metadata.json
- shared/output/cloud/vision_v1/.yardopts
- shared/output/cloud/vision_v1/README.md
- shared/output/cloud/vision_v1/google-cloud-vision-v1.gemspec
- shared/output/cloud/vision_v1/proto_docs/README.md
- shared/output/gapic/templates/showcase/.yardopts
- shared/output/gapic/templates/showcase/README.md
- shared/output/gapic/templates/showcase/google-showcase.gemspec
- shared/output/gapic/templates/showcase/proto_docs/README.md
The intent here is to pull as much metadata as possible from service_yaml so we don't have to set fields in the bazel build rules when onboarding new clients. This pulls service yaml information into the `Gapic::Model::ApiMetadata` object, which is then queried from the presenters. Currently, information from configs (i.e. from bazel rules) still takes precedence, but then ApiMetadata is consulted.
> feat: Honor metadata from the service yaml

- .toys/.toys.rb
- gapic-common/.toys.rb
- gapic-generator-ads/.toys.rb
- gapic-generator-cloud/.toys.rb
- gapic-generator/.toys.rb
- gapic/.toys.rb
- shared/.toys.rb
Implements:
* `toys bundle install` to replace `bundle exec rake bundle`.
* `toys bundle update` to replace `bundle exec rake bundleupdate`.
* `toys ci` to replace `bundle exec rake ci`
* `toys test` to replace `bundle exec rake test`
* `toys rubocop` to replace `bundle exec rake rubocop`
* `toys gen` to replace `bundle exec rake gen`. There is also `toys gen showcase` and `toys gen garbage`.
* `toys bin` to replace `bundle exec rake bin`. There is also `toys bin showcase` and `toys bin garbage`.
Also implements `toys test` and `toys rubocop` within each directory. However, per-directory `gen` and `bin` are still implemented as rake tasks.
Note also that toys does not require a toplevel bundle. Once we have all toplevel rake tasks ported, we can get rid of the toplevel Gemfile. Currently, …
> chore: Add toys tools for various workflows

- gapic-generator/lib/gapic/model/api_metadata.rb
- gapic-generator/test/gapic/model/api_metadata_test.rb
- gapic-generator/test/gapic/schema/service_config_parser_test.rb
fixes #933
fixes https://github.com/googleapis/google-cloud-ruby/issues/20567
> fix: Remove html tags from description text parsed from service yaml

- gapic-generator-cloud/templates/cloud/gem/readme.erb
- gapic-generator-cloud/templates/cloud/wrapper_gem/readme.erb
- shared/output/cloud/grafeas_v1/README.md
- shared/output/cloud/language_v1/README.md
- shared/output/cloud/language_v1beta1/README.md
- shared/output/cloud/language_v1beta2/README.md
- shared/output/cloud/location/README.md
- shared/output/cloud/secretmanager_v1beta1/README.md
- shared/output/cloud/secretmanager_wrapper/README.md
- shared/output/cloud/speech_v1/README.md
- shared/output/cloud/vision_v1/README.md
> fix: Fix broken ruby-doc logger class links in readme templates

- gapic-generator-cloud/lib/gapic/presenters/wrapper_service_presenter.rb
fixes #895 
I audited existing usage and determined that, in addition to `google-cloud-gsuite_add_ons`, the `google-cloud-automl` wrapper is also affected. A factory method name will change from `auto_ml` to `automl`. Generally we do want this change, but I opened https://github.com/googleapis/google-cloud-ruby/pull/20587 to ensure backward compatibility.
> fix: Path override now affects wrapper factory method names

- gapic-common/lib/gapic/protobuf.rb
- gapic-common/test/gapic/protobuf/coerce_test.rb
A field that appears in a Hash as nil breaks coercing the Hash with an error like: "Value  must be a Hash or a Foo (ArgumentError)".
For example, the version `0.19.0` of `gapic-common` breaks `google-cloud-firestore`.
Running this:
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'dotenv'
gem 'gapic-common', '0.19.0'
gem 'google-cloud-firestore', '2.13.0'
end
require 'dotenv/load'
require 'google/cloud/firestore'
firestore = Google::Cloud::Firestore.new(project_id: ENV.fetch('PROJECT_ID'))
doc = firestore.doc(ENV.fetch('DOCUMENT_ID'))
puts doc.get
```
Results in an error like:
```
/home/psyho/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gapic-common-0.19.0/lib/gapic/protobuf.rb:39:in `coerce': Value  must be a Hash or a …
```
> Fix handling of optional fields in coerce

- gapic-common/lib/gapic/grpc/service_stub.rb
- gapic-common/lib/gapic/rest/client_stub.rb
- gapic-common/lib/gapic/universe_domain_concerns.rb
- gapic-common/test/gapic/grpc/service_stub_test.rb
- gapic-common/test/gapic/grpc/stub_test.rb
- gapic-common/test/gapic/rest/client_stub_test.rb
Partial support for universe domains in GAPICs. This pull request includes changes to gapic-common.
* Adds optional `universe_domain` and `endpoint_template` arguments to stub class constructors. The former is the universe domain in which the call should take place (falling back to the `GOOGLE_CLOUD_UNIVERSE_DOMAIN` environment variable, then defaulting to `googleapis.com`). The latter is a template of the endpoint host in which the universe domain component has been replaced with `$UNIVERSE_DOMAIN$` (expressed in the constant `Gapic::UniverseDomainConcerns::ENDPOINT_SUBSTITUTION`). If the latter is not present, the existing `endpoint` argument is used.
* Implements determining the endpoint given the universe domain and template.
* Provides accessors for the universe domain and endpoint …
> feat(gapic-common): Honor universe domain in stubs

- gapic-common/lib/gapic/universe_domain_concerns.rb
Fixes `uninitialized constant Gapic::Common (NameError)` in `class UniverseDomainMismatch < ::Gapic::Common::Error`
> fix(gapic-generator-ruby): add missing module import for universe_domain_concerns

- gapic-generator/lib/gapic/presenters/enum_presenter.rb
- gapic-generator/lib/gapic/presenters/field_presenter.rb
- gapic-generator/lib/gapic/presenters/message_presenter.rb
- gapic-generator/lib/gapic/presenters/method_presenter.rb
- gapic-generator/lib/gapic/presenters/method_rest_presenter.rb
- gapic-generator/lib/gapic/presenters/service_presenter.rb
- gapic-generator/lib/gapic/presenters/service_rest_presenter.rb
- gapic-generator/lib/gapic/schema/wrappers.rb
- gapic-generator/lib/google/cloud/tools/snippetgen/configlanguage/v1/snippet_config_language_pb.rb
- gapic-generator/lib/google/cloud/tools/snippetgen/snippetindex/v1/snippet_index_pb.rb
- gapic-generator/lib/google/protobuf/compiler/plugin_pb.rb
- gapic-generator/templates/default/lib/_service.erb
- gapic-generator/templates/default/proto_docs/_deprecated.erb
- gapic-generator/templates/default/proto_docs/_enum.erb
- gapic-generator/templates/default/proto_docs/_message.erb
- gapic-generator/templates/default/service/client/_client.erb
- gapic-generator/templates/default/service/client/method/_def.erb
- gapic-generator/templates/default/service/client/method/docs/_deprecated.erb
- gapic-generator/templates/default/service/rest/client/_client.erb
- gapic-generator/templates/default/service/rest/service_stub/_service_stub.erb
- shared/output/ads/googleads/proto_docs/google/ads/googleads/v12/common/bidding.rb
- shared/output/cloud/speech_v1/proto_docs/google/cloud/speech/v1/cloud_speech.rb
- shared/output/cloud/vision_v1/proto_docs/google/cloud/vision/v1/image_annotator.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/deprecated_service.rb
Changelog:
- Generates @deprecated tag based on proto inputs.
- Some rubocop fixes & other docstring formatting.
Closes #992
> feat(gapic-generator-ruby): add @deprecated tags to document items

- gapic-generator-cloud/templates/cloud/wrapper_gem/_main.erb
- shared/output/cloud/compute_small_wrapper/lib/google/cloud/compute.rb
- shared/output/cloud/language_wrapper/lib/google/cloud/language.rb
- shared/output/cloud/secretmanager_wrapper/lib/google/cloud/secret_manager.rb
Updates the configs for wrapper clients to "activate" universe domain support. This effectively ensures the endpoint (override) configuration defaults to nil so that the universe domain logic to determine the endpoint will kick in—that is, we no longer "override" the universe domain endpoint with the google default universe endpoint. It also provides a universe domain configuration at the wrapper level so that users can set a universe domain configuration in code that applies to all service versions under the wrapper.
NB. Wrappers generated with this change are _incompatible_ with GAPICs that do not have universe_domain support. This is because of an idiosyncrasy of how config overriding takes place: if a wrapper is present, its endpoint config actually provides the "final" default …
> fix: Update wrapper configs for universe_domain support

- README.md
- gapic-generator-ads/README.md
- gapic-generator-cloud/README.md
- gapic-generator/README.md
- shared/README.md
Reworks the readmes in the gapic-generator, gapic-generator-cloud, and gapic-generator-ads directories, so that:
* They are up to date for current usage
* They no longer reference rakefiles or other tools that are no longer present
* They make sense for the gem releases
Closes #1033.
> chore: Update readmes

- shared/test/showcase/test_helper.rb
Fetches and executes `gapic-showcase` based on releases instead of relying on docker images. This approach is used in other generators already (such as in `gapic-generator-go`).
Added logic to not spawn a new server if one is already running.
Fixes #1038
> feat(gapic-showcase): remove dependency on gapic-showcase docker images for tests

- gapic-generator-cloud/test/test_helper.rb
We are still missing requiring it in test_helper for CloudApiTest. This unblocks a generator release (v0.30.0, PR #1067): https://github.com/googleapis/gapic-generator-ruby/actions/runs/8823686423/job/24224662659?pr=1067
> fix: Require OpenStruct in CloudApiTest

- gapic-generator/lib/gapic/presenters/enum_value_presenter.rb
- gapic-generator/test/gapic/presenters/enum_presenter_test.rb
- shared/output/gapic/templates/garbage/proto_docs/garbage/garbage.rb
A slight change from #1061 in order to be compatible with yard. It now uses the module name instead of `self`.
> feat: Use module name to prevent keyword collision with enum values

- gapic-generator/gapic-generator.gemspec
This PR updates the gemspec to add an explicit dependency on the [bigdecimal gem](https://rubygems.org/gems/bigdecimal). This resolves the following warning:
```
warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec.
```
> chore: Resolve BigDecimal warning

- gapic-common/lib/gapic/common/polling_harness.rb
- gapic-common/lib/gapic/common/retry_policy.rb
- gapic-common/test/gapic/common/polling_harness_test.rb
- gapic-common/test/gapic/common/retry_policy_test.rb
Re-opening this PR after moving all changes to a new `gapic-polling-harness` branch. The polling harness logic was originally reverted in #1083. We will keep all changes in `gapic-polling-harness` for later usage.
**Original PR #1081 description:**
Start supporting timeouts in the gapic polling harness. 
It removes the need for clients to keep track of their own time variables, as it is done [here](https://github.com/googleapis/google-cloud-ruby/blob/2408f6614065c56046f557b67a29dffc6c43c931/google-cloud-bigtable/lib/google/cloud/bigtable/table.rb#L569) in bigtable.
Note: timeout deadline is calculated based on when the method `wait` is called. Late initialization can cause off-by-one errors.
Next PR integrates this change for testing in bigtable.
> feat: Support timeout-based polling

- gapic-generator-cloud/lib/gapic/presenters/wrapper_gem_presenter.rb
- gapic-generator-cloud/test/gapic/presenters/wrapper_gem_presenter_test.rb
- gapic-generator/lib/gapic/presenters/gem_presenter.rb
- gapic-generator/test/gapic/formatting_utils_test.rb
Relates to https://github.com/googleapis/google-cloud-ruby/pull/26629
Pass a `true` value for `disable_xrefs` in other to avoid broken reference to versioned gems, from the wrapper gems.
> feat: Disable xrefs for README files

- gapic-generator/lib/gapic/path_pattern/parser.rb
- gapic-generator/lib/gapic/path_pattern/segment.rb
- gapic-generator/test/gapic/presenters/pattern_presenter_test.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/resource_names/paths.rb
- shared/output/gapic/templates/garbage/test/so/much/trash/resource_names_paths_test.rb
Reverting changes from https://github.com/googleapis/gapic-generator-ruby/pull/1096 and adding `binding.local_variable_get` for collisions from the generator.
> feat: Support local binding for variables with keyword collision

- gapic-generator/lib/gapic/presenters/resource_presenter.rb
- gapic-generator/templates/default/service/client/resource/_def.erb
- gapic-generator/test/gapic/presenters/pattern_presenter_test.rb
Addressing the last part of local binding causing an issue in https://github.com/googleapis/google-cloud-ruby/pull/27013
The name needs to be the original argument name within the string, so I am creating a separate method within the presenter to escape it.
This is part of `resource/_def.erb`.
Previous implementation in #1110
> fix: Add missing local binding in resource path methods

- gapic-common/.rubocop.yml
- gapic-common/lib/gapic/headers.rb
- gapic-common/lib/gapic/universe_domain_concerns.rb
- gapic-common/test/gapic/grpc/service_stub_test.rb
This is Ruby's response to internal issue b/349488459. In a separate PR for the auth library (https://github.com/googleapis/google-auth-library-ruby/pull/493), we add a (temporary, optional) attribute (`disable_universe_domain_check`) to credential objects that signals the credential may incorrectly claim googleapis as its universe domain. This will be used for GCECredentials temporarily; when set (which for now it will be), GCECredentials will not query the metadata server for universe domain but will instead hard-code `googleapis.com`. Then, this PR for gapic-common will check for the `disable_universe_domain_check` attribute, and if present and set, will not perform the universe domain consistency check. This will effectively stop universe domain MDS calls and checks for GCE …
> feat: Disable universe domain check if credentials include an explicit request to do so

- gapic-generator/lib/gapic/generators/default_generator.rb
Fixes #1115
We have a couple gems affected by this -- I will clean up the post-processing once it is live.
> feat: Remove path tests for clients using REST without gRPC

- gapic-generator/.rubocop.yml
Currently failing in https://github.com/googleapis/gapic-generator-ruby/actions/runs/11507777942/job/32035472718?pr=1122
> chore: Disable safe navigation lint in gapic-generator

- gapic-generator-cloud/templates/cloud/wrapper_gem/client_test.erb
- gapic-generator/lib/gapic/model/service/nonstandard_lro_provider.rb
- shared/output/cloud/compute_small_wrapper/test/google/cloud/compute/client_test.rb
- shared/output/cloud/language_wrapper/test/google/cloud/language/client_test.rb
- shared/output/cloud/secretmanager_wrapper/test/google/cloud/secret_manager/client_test.rb
Necessary for wrapper gem tests when the corresponding gapic has logger methods
> fix: fix wrapper gem tests by stubbing the stub_logger method

- gapic-generator/templates/default/service/rest/client/method/def/_response_nonstandard_lro.erb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/addresses/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/networks/rest/client.rb
- shared/output/cloud/compute_small/lib/google/cloud/compute/v1/region_instance_group_managers/rest/client.rb
- shared/output/gapic/templates/testing/lib/testing/nonstandard_lro_grpc/all_subclients_consumer/rest/client.rb
- shared/output/gapic/templates/testing/lib/testing/nonstandard_lro_grpc/plain_lro_consumer/rest/client.rb
The logging work changed the way RPC methods should specify custom result objects. Instead of returning the new object out of the block (which short-circuits the postprocessing that the logging depends on), we instead `throw` the new object which is then caught by new code in gapic-common. So all the code paths that want to change the result object should have been changed to throw the new object. Unfortunately I missed the REST case with nonstandard LRO. This is the reason the acceptance tests on https://github.com/googleapis/google-cloud-ruby/pull/27799 are currently failing: because the wrong object is being returned from methods that use nonstandard LROs.
> fix: Throw the correct result object for REST with nonstandard LRO

- gapic-generator/lib/gapic/schema/loader.rb
- gapic-generator/lib/gapic/schema/wrappers.rb
- gapic-generator/test/gapic/presenters/field_presenter_test.rb
- shared/output/ads/googleads/proto_docs/google/ads/googleads/v15/resources/campaign.rb
- shared/output/ads/googleads/proto_docs/google/ads/googleads/v15/services/campaign_service.rb
- shared/output/cloud/grafeas_v1/proto_docs/google/protobuf/struct.rb
- shared/output/cloud/grafeas_v1/proto_docs/grafeas/v1/grafeas.rb
- shared/output/cloud/grafeas_v1/proto_docs/grafeas/v1/intoto_statement.rb
- shared/output/cloud/grafeas_v1/proto_docs/grafeas/v1/provenance.rb
- shared/output/cloud/language_v1/proto_docs/google/cloud/language/v1/language_service.rb
- shared/output/cloud/language_v1beta1/proto_docs/google/cloud/language/v1beta1/language_service.rb
- shared/output/cloud/language_v1beta2/proto_docs/google/cloud/language/v1beta2/language_service.rb
- shared/output/cloud/secretmanager_v1beta1/proto_docs/google/cloud/secrets/v1beta1/resources.rb
- shared/output/cloud/speech_v1/proto_docs/google/cloud/speech/v1/cloud_speech.rb
- shared/output/cloud/speech_v1/proto_docs/google/longrunning/operations.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/client.rb
- shared/output/cloud/vision_v1/lib/google/cloud/vision/v1/product_search/rest/client.rb
- shared/output/cloud/vision_v1/proto_docs/google/cloud/vision/v1/product_search_service.rb
- shared/output/cloud/vision_v1/proto_docs/google/longrunning/operations.rb
- shared/output/gapic/templates/garbage/lib/so/much/trash/garbage_service/client.rb
- shared/output/gapic/templates/garbage/proto_docs/garbage/garbage.rb
- shared/output/gapic/templates/garbage/proto_docs/google/longrunning/operations.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/client.rb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/client.rb
- shared/output/gapic/templates/showcase/proto_docs/google/longrunning/operations.rb
- shared/output/gapic/templates/showcase/proto_docs/google/showcase/v1beta1/echo.rb
- shared/output/gapic/templates/showcase/proto_docs/google/showcase/v1beta1/messaging.rb
- shared/output/gapic/templates/testing/proto_docs/google/longrunning/operations.rb
The interesting commit is the first. (The second commit is just regeneration of the goldens based on the changes in the first.)
> feat(gapic-generator): Add clarifying notes to oneof members in proto_docs

- .github/workflows/tag-generators.yml
The googleapis org changed the github actions token permissions to the restricted setting, which broke several of our actions that require certain write permissions. This PR restores functionality of the tag-generators action by specifying the needed permissions explicitly.
> chore: Grant needed permissions to actions

- gapic-generator-cloud/templates/cloud/wrapper_gem/_main.erb
- gapic-generator-cloud/templates/cloud/wrapper_gem/client_test.erb
- gapic-generator-cloud/templates/cloud/wrapper_gem/readme.erb
- shared/output/cloud/compute_small_wrapper/README.md
- shared/output/cloud/compute_small_wrapper/lib/google/cloud/compute.rb
- shared/output/cloud/compute_small_wrapper/test/google/cloud/compute/client_test.rb
- shared/output/cloud/language_wrapper/README.md
- shared/output/cloud/language_wrapper/lib/google/cloud/language.rb
- shared/output/cloud/language_wrapper/test/google/cloud/language/client_test.rb
- shared/output/cloud/secretmanager_wrapper/README.md
- shared/output/cloud/secretmanager_wrapper/lib/google/cloud/secret_manager.rb
- shared/output/cloud/secretmanager_wrapper/test/google/cloud/secret_manager/client_test.rb
Currently the client object factory methods in wrapper clients just expect that the underlying GAPIC provides the correct classes, and will raise LoadErrors or NameErrors if used with an out-of-date GAPIC. In particular, the unit tests for wrappers will fail if the GAPIC is out of date. This causes problems when a new service is added to an API, and gets added to the GAPIC and wrapper simultaneously. The wrapper tests fail until the GAPIC is updated and released, and we also typically go through the extra step of updating the version requirement in the dependency. This is a recurring source of toil.
This PR improves the situation by:
* Providing additional documentation calling out that an out-of-date GAPIC could cause the wrapper's factory method to fail, and noting what should be done. …
> feat(cloud): Wrapper clients provide better introspection to determine availability of client objects

- gapic-generator-cloud/test/gapic/presenters/method/regapic_paged_test.rb
- gapic-generator/lib/gapic/presenters/method_presenter.rb
- gapic-generator/lib/gapic/presenters/method_rest_presenter.rb
- gapic-generator/lib/gapic/presenters/service_presenter.rb
- gapic-generator/templates/default/service/rest/client/method/def/_response_paged.erb
- shared/output/gapic/templates/showcase/lib/google/showcase/v1beta1/echo/rest/client.rb
See internal issue b/382502247. This updates the pagination detection algorithm for REST/REGAPIC clients so it complies with AIP-158. It does not affect compute, which should remain on the custom algorithm.
This will cause breaking changes in 70-ish GAPICs, where pagination behavior for some REST RPC methods will change. Thus, this should be merged and applied with care.
> feat(gapic-generator): Change REGAPIC pagination algorithm to the standard algorithm for non-compute clients

- .github/workflows/ci.yml
- gapic-generator-ads/Gemfile.lock
- gapic-generator-cloud/Gemfile.lock
- gapic-generator/Gemfile.lock
- rules_ruby_gapic/gapic-generator-ads/repositories.bzl
- rules_ruby_gapic/gapic-generator-cloud/repositories.bzl
- rules_ruby_gapic/gapic-generator/repositories.bzl
- rules_ruby_gapic/prebuilt/pack_prebuilt_ruby.sh
- rules_ruby_gapic/repositories.bzl
Change the Ruby version used by Bazel to 3.2.8. Also updates the gemfiles to reflect the default bundler on Ruby 3.2.8, and updates the CI to test against Ruby 3.2.
Includes a prebuilt binary for Ruby 3.2.8, but this will need to be updated (in a separate PR) for the docker container used by bazelbot.
This is intended as an interim update. The goal is to update Rails to 8.0 (see #1173) and Ruby to 3.4, but we cannot do either of those immediately because Rails 8.0 cannot run on the current Ruby 3.1.3, and the current Rails 5.2 cannot run on Ruby 3.4. So we will first update Ruby to 3.2, then update Rails, then finally update Ruby again to 3.4.
> feat: Update Ruby to 3.2.8
